### ISSUE TITLE
allow ! in exceptions configuration

### ISSUE THREAD

**Issue by Mariusthvdb** [maykar/custom-header#100]
please consider as per title, to be able to do:

```
conditions:
  user_agent: ! Chrome
config:
  hide_tabs: 30
```

would shorten the config a lot, since I now have to use the opposite, and use show_tabs for all tabs displayed in the case the browser is not Chrome ;-)
please see: https://community.home-assistant.io/t/custom-header/155399/346?u=mariusthvdb

Think the ! might be very nice to have in the other configs as well.

Thanks for considering
