### ISSUE TITLE
hide_tabs not working in exceptions when using comma separated list

### ISSUE THREAD

**Issue by Glivmo** [maykar/custom-header#103]
This is probably related to #68  

Whenever I use a comma separated list of tabs, hide_tabs does not work. When i change back to an array of tabs, it works again.

This causes the issue that the UI editor does not work for me, because every time you click "Save and reload" on the UI editor, it changes hide_tabs to a comma separated list.

This works:
```YAML
- conditions:
    user: Test
  config:
    default_tab: Home
    hide_tabs: 
      - Settings
      - Test View
```

This doesn't:
```YAML
- conditions:
    user: Test
  config:
    default_tab: Home
    hide_tabs: 'Settings,Test View'
```
