### ISSUE TITLE
error in log 'querySelector'

### ISSUE THREAD

**Issue by kernehed** [maykar/custom-header#104]
I got this error in the log:
`/community_plugin/custom-header/custom-header.js:1:7028 Uncaught TypeError: Cannot read property 'querySelector' of undefined`

I just switched from your depreciated Custom Header to the new one.
My ui-lovelace.yaml: 
```
custom_header:
  compact_mode: true
resources:
  - url: /community_plugin/custom-header/custom-header.js
    type: module
title: Kernehed Manison
views:
```
