### ISSUE TITLE
Sticky header/footer

### ISSUE THREAD

**Issue by dooz127** [maykar/custom-header#114]
I'd like to have a single navigation bar for hass and can achieve that by recreating each of the panels as views like so:

```yaml
  - title: Map
    path: ../map
    icon: 'mdi:map'
    panel: true
    badges: []
    cards: []
  - title: Logbook
    path: ../logbook
    icon: 'mdi:format-list-bulleted-type'
    badges: []
    cards: []
    panel: true
  - title: History
    path: ../history
    icon: 'mdi:chart-timeline'
    panel: true
    badges: []
    cards: []
  - title: Community
    path: ../hacs/installed
    icon: 'mdi:alpha-c-box'
    badges: []
    cards: []
    panel: true
  - title: Developer Tools
    path: ../developer-tools/info
    icon: 'mdi:hammer'
    panel: true
    badges: []
    cards: []
  - title: Profile
    path: ../profile
    icon: 'mdi:account'
    panel: true
    badges: []
    cards: []
  - panel: true
    title: Configuration
    path: ../config/dashboard
    icon: 'mdi:settings'
    badges: []
    cards: []
```
![image](https://user-images.githubusercontent.com/19983618/73041695-46b83700-3e13-11ea-9a8b-d7304d28162d.png)

The only problem is when you navigate to the panels, it's hard to navigate back to lovelace views so it'd be cool if there was an option to make the header/footer sticky, i.e., persist even when navigating to one of the panels (e.g., maps, logbook, history, etc.).

**Comment by dooz127** [comment]
I can achieve the same thing by setting 'Always hide the sidebar' in Profile and then making each panel an IFrame card, e.g.:

```yaml
  - badges: []
    cards:
      - type: iframe
        url: ../map
        aspect_ratio: 100%
    icon: 'mdi:map'
    panel: true
    path: map
    title: Map
  - badges: []
    cards:
      - type: iframe
        url: ../logbook
        aspect_ratio: 100%
    icon: 'mdi:format-list-bulleted-type'
    panel: true
    path: logbook
    title: Logbook
  - badges: []
    cards:
      - type: iframe
        url: ../history
        aspect_ratio: 100%
    icon: 'mdi:chart-timeline'
    panel: true
    path: history
    title: History
  - badges: []
    cards:
      - type: iframe
        url: ../hacs/installed
        aspect_ratio: 100%
    icon: 'mdi:alpha-c-box'
    panel: true
    path: hacs
    title: Community
  - badges: []
    cards:
      - type: iframe
        url: ../developer-tools/info
        aspect_ratio: 100%
    icon: 'mdi:hammer'
    panel: true
    path: developer-tools
    title: Developer Tools
  - badges: []
    cards:
      - type: iframe
        url: ../profile
        aspect_ratio: 100%
    icon: 'mdi:account'
    panel: true
    path: profile
    title: Profile
  - badges: []
    cards:
      - type: iframe
        url: ../config/dashboard
        aspect_ratio: 100%
    icon: 'mdi:settings'
    panel: true
    path: config
    title: Configuration
```
