### ISSUE TITLE
Elevated error logs on v1.2.2

### ISSUE THREAD

**Issue by WhoSayIn** [maykar/custom-header#116]
Hi,

I don't remember seeing this error before I updated to v1.2.2, it just happens randomly. (All my views have titles.)

`https://hassio.local:8123/community_plugin/custom-header/custom-header.js:1:10068 TypeError: undefined is not an object (evaluating 'lovelace$1().config.views[lovelace$1().current_view].title')`

Custom Header config;
```
custom_header:
  background: 'rgba(155, 155, 155, 0.8)'
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
  compact_mode: true
  swipe_animate: fade
  swipe_prevent_default: true
```

Home Assistant 0.104.3
HassOS v3.8
Safari 12.0.3 on Mac OS Mojave
