### ISSUE TITLE
UI not saving exceptions configs correctly

### ISSUE THREAD

**Issue by calebmah** [maykar/custom-header#136]
Editing the toggles in the UI for exceptions does not seem to save the correct configuration in the raw config editor. Also, it seems like the UI is not displaying the configured settings correctly as well. 

For instance, with the config: 
```
custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: User
      config:
        disabled_mode: false
        show_tabs: 0 to 3
        hide_config: false
        hide_help: false
        menu_hide: false
        voice_hide: false
        options_hide: false
        hide_unused: false
        hide_raw: false
        chevrons: true
  show_tabs: main
  hide_config: true
  chevrons: false
  hide_help: true
  hide_unused: true
  hide_raw: true
  options_hide: true
  voice_hide: true
  menu_hide: true
  default_tab: main
```
I get this in the UI. As seen, the toggles in the config section do not match with the settings in the raw editor, although the other sections are ok.

![image](https://user-images.githubusercontent.com/21040892/74851084-b91a2980-5375-11ea-9151-1b805734837b.png)

When trying to edit the exception through the UI, after saving the settings sometimes do not get saved at all, and instead saves as something like:
```
custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: User
      config: {}
```

This is using chrome running v1.3.2 on hassio 105.5, but had the same issue on 105.2 as well.
