### ISSUE TITLE
Console reports a problem with polyfill being loaded multiple times.

### ISSUE THREAD

**Issue by fribse** [maykar/custom-header#139]
I'm seeing this message when I load pages:

`@babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.`

The config:
```
custom_header:
  compact_mode: true
  header_text: Fribert Home
  voice_hide: true
```

HA: 0.106.2
Custom Header: 1.3.2
Firefox: 73.0.1
