### ISSUE TITLE
Button of the selected view isn't underlined.

### ISSUE THREAD

**Issue by alexmail34** [maykar/custom-header#142]
How the button of the selected view looks like upon loading the page:
![Screenshot 2020-03-03 at 23 47 57](https://user-images.githubusercontent.com/5776131/75827288-97736600-5da9-11ea-96fa-79281a0df8a1.png)

How the selected button **should** look like. Currently works only after you click it. 
![Screenshot 2020-03-03 at 23 49 54](https://user-images.githubusercontent.com/5776131/75827426-f2a55880-5da9-11ea-8c6b-460d9529da77.png)

```
custom_header:
  hidden_tab_redirect: false
  shadow: false
  editor_warnings: false
  compact_mode: true
  button_text:
    options: '{{ time }}'
resources:
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  - type: js
    url: /local/synthwave-hass-extras.js
  - url: /community_plugin/custom-header/custom-header.js
    type: module
title: ''
views:
  - icon: 'mdi:home'
    panel: false
    path: default_view
    theme: Backend-selected
    title: Home
    badges: []
    cards:
      - entity: light.bedroom_lights
        theme: Backend-selected
        type: light
      - entities:
          - entity: light.bedside
          - entity: light.desk
          - entity: light.ceiling
        show_header_toggle: false
        title: Lights
        type: entities
      - entities:
          - entity: media_player.bedroom
            group: true
            type: 'custom:mini-media-player'
        type: entities
      - entity: weather.home
        theme: Backend-selected
        type: weather-forecast
      - entities:
          - entity: scene.chores
          - entity: scene.everyday
          - entity: scene.computer_time
        show_header_toggle: false
        title: Scene Selector
        type: entities
      - entities:
          - entity: sensor.czech_republic_coronavirus_confirmed
            icon: 'mdi:emoticon-neutral-outline'
            name: Confirmed
          - entity: sensor.czech_republic_coronavirus_current
            icon: 'mdi:emoticon-frown-outline'
            name: Current
          - entity: sensor.czech_republic_coronavirus_recovered
            icon: 'mdi:emoticon-happy-outline'
            name: Recovered
          - entity: sensor.czech_republic_coronavirus_deaths
            icon: 'mdi:emoticon-dead-outline'
            name: Deaths
        show_icon: true
        show_name: true
        show_state: true
        type: glance
        title: COVID-19
  - title: Lights
    path: lights
    icon: 'mdi:lightbulb'
    theme: synthwave
    badges: []
    cards: []
```
Using Home Assistant 0.106.4
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

Tried disabling the plugin and the issue doesn't persist, so perhaps it must be bug of the plugin. 

Thank you very much for this plugin.
