### ISSUE TITLE
button_text options date/time causes page to jump to top on time change

### ISSUE THREAD

**Issue by danodemano** [maykar/custom-header#143]
This configuration:

```
custom_header:
  button_text:
    options: '{{ hours24LZ }}:{{ minutesLZ }}<br>{{ date }}'
  compact_mode: true
  hide_help: true
```

Causes the page to jump to the top when the time updates.  It's not a major issue on desktop as I try to keep my views to a single screen with no scrolling required.  It's highly annoying on mobile though where scrolling down will randomly jump back to the top as the time changes.  Let me know if more information is required.  

HA 0.106.4 and CH 1.3.2 installed through HACS.  Browsers tried are Chrome, Brave, and Firefox current versions.  Disabling CH resolves this problem.
