### ISSUE TITLE
HASS 0.107+

### ISSUE THREAD

**Issue by roblandry** [maykar/custom-header#147]
*  Lovelace config:
```
lovelace:
  mode: storage
  dashboards:
    user:
      mode: yaml
      title: User
      icon: mdi:view-dashboard
      show_in_sidebar: true
      filename: lovelace_user.yaml
    admin:
      mode: yaml
      title: Admin
      icon: mdi:shield-account
      show_in_sidebar: true
      filename: lovelace_admin.yaml
      require_admin: true
```

*  A copy/paste of your Custom Header config
```
custom_header:
  compact_mode: true
  hide_help: true
  voice_hide: true
  menu_dropdown: true
```
*  Any errors relevant to Custom Header found in the HA logs
None

*  Any relevant errors found in your browsers dev console (usually found by hitting F12)
None

*  The version of Home Assistant and Custom Header you are using
Hass: 0.107.0b0
CH: 1.32

*  The browser type your are using
Chrome (Version 80.0.3987.122 (Official Build) (64-bit)) on Ubuntu 19.10

*  Issue:
In home assistant [0.107](https://rc.home-assistant.io/blog/2020/03/10/release-107/) lovelace allows for multiple panels. ~~This creates an issue where custom-header ONLY works for panels that have a path of "lovelace" ie. (https://mydomain.com/lovelace/0). If you create additional panels custom-header is not applied to the panels. In my configuration i am creating a "user" (https://mydomain.com/user/0) and an "admin" (https://mydomain.com/admin/0) panel, neither of which apply the custom-header despite the resources being applied.~~

  ~~Possibly additional config options can be created allowing the user to define which panels to apply the custom header to ie.~~
```
custom_header:
  panels:
    - admin
    - user
    - any_panel_name
```

Edit:
Actually, it appears to be working, but browser caching is the issue. You cannot simply select the menu  and have the custom header applied, it requires refreshing the page.
