### ISSUE TITLE
Why does my compact header not working? 

### ISSUE THREAD

**Issue by haianhlc99** [maykar/custom-header#150]
I dont know where is the problem of my raw config, please helpme
```
custom_header:
  compact_mode: true
resources:
- type: module
   url: /local/custom-lovelace/custom-header/custom-header.js?v=0.0.1
```
I am using Home assistant ver 0.93 and newest Custom Header
