### ISSUE TITLE
On page load to a specific tab it cuts off the text

### ISSUE THREAD

**Issue by iptvcld** [maykar/custom-header#151]
![Screenshot_20200323-235436](https://user-images.githubusercontent.com/34818686/77392785-18eb6200-6d72-11ea-92c1-61070a5a68ea.jpg)

As per screenshot, page loads to summary and the text gets cut off.

**Comment by maykar** [comment]
Please try the latest version and report back:

https://community.home-assistant.io/t/custom-header/155399/636

**Comment by iptvcld** [comment]
Just installed the updated version and it is ignoring the mobile exception i have
`custom_header:
  compact_mode: true
  hide_help: true
  voice_hide: true
  options_hide: false
  sidebar_closed: true
  active_tab_color: black
  tab_indicator_color: red
  all_tabs_color: "#6B6C6C"
  button_color:
    options: black
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        tab_indicator_color: green
        background:
        default_tab: 11
        active_tab_color: black
        all_tabs_color:
        disable_sidebar: false
        menu_hide: false`

**Comment by maykar** [comment]
Make a new issue with all the required information. Has this issue been resolved?

**Comment by iptvcld** [comment]
it has not been resolved; the text still gets cut off and ignores the mobile user_agent. 
I have gone back to the previous version for now

**Comment by maykar** [comment]
Would love to know if you get any errors in HA logs or in your browsers dev-tools all mentioned in the bot's link in the first reply. 

This issue and your new issue of mobile exception provide very little information other than your config and that it doesn't work. I can't fix things without info.

**Comment by iptvcld** [comment]
I have checked my logs and it is not reporting anything.  I updated to your new pre-release and by default under mobile exception i have it set to load on tab 11.  SO right away i noticed that was not happening and the text was still being cut off. 

I opened my HA in incognito tab and same thing, was ignoring the mobile aspect.

I installed the 1.3.2 again and text is still cut off but atleast it does not ignore my mobile exception area.

With the new version even i change the tab_indicator_color: to green it does not see that

**Comment by maykar** [comment]
This is the info from the bots link above that still haven't been answered:

* Any relevant errors found in your browsers dev console (usually found by hitting F12)
* The browser type your are using

Does it only happen in a certain browser or all browsers that you have tried.

If there are any errors in your browser's dev-tools they would point me in the correct direction.

**Comment by iptvcld** [comment]
If it is working for you then im sure i have done something wring. Do you use user_agent: Mobile and does it show you the mobile exceptions? This way i will know its on my end only.
I am using Chrome on my mobile (old version sees the exceptions) the desktop version is fine

**Comment by maykar** [comment]
Mobile exceptions are working for me in chrome on Android, the tab issue is fixed for me as well. I did notice something strange with your mobile device config though. The `background:` config is blank.

```
    - conditions:
        user_agent: Mobile
      config:
        tab_indicator_color: green
        background:
```

**Comment by iptvcld** [comment]
the background i left blank because i have a background set for the non-mobile view and on the mobile; i just want the default.

**Comment by maykar** [comment]
Okay that should work.

`sidebar_closed` is no longer an option and button color config has changed since CCH

I've updated your config. Not sure if it will help, but it's worth a shot.

```
custom_header:
  compact_mode: true
  hide_help: true
  voice_hide: true
  options_hide: false
  options_color: black
  active_tab_color: black
  tab_indicator_color: red
  all_tabs_color: "#6B6C6C"
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        tab_indicator_color: green
        background:
        default_tab: 11
        active_tab_color: black
        all_tabs_color:
        disable_sidebar: false
        menu_hide: false
```
