### ISSUE TITLE
Double header after dismissing Configure UI

### ISSUE THREAD

**Issue by gadgetchnnel** [maykar/custom-header#154]
In Custom Header version 1.3.6 (on HA 0.107.7) if the following steps are performed:

1. Click on Configure UI
2. Click on the close button in the top-left corner

The header is doubled up like this:

<img width="1380" alt="Screenshot 2020-03-28 at 14 42 08" src="https://user-images.githubusercontent.com/2099542/77825618-5cdbbf80-7102-11ea-8b24-d5e9f2516b6f.png">

Sometimes, the double header will only display briefly (this seems to be more likely if cards are edited between steps 1 and 2) but it more often needs a refresh to make it go away.

Here is the config:

```
custom_header:
  button_text:
    options: >-
      {{ hours12 }}:{{ minutesLZ }} {{ AMPM }} - <ha-icon icon='mdi:weather-{%-
      if is_state('weather.dark_sky', 'partlycloudy') -%}partly-cloudy {%- elif
      is_state('weather.dark_sky', 'clear-night') -%}night {%- else
      -%}{{states('weather.dark_sky')}}{%- endif -%}'
      style='top:-3px;'></ha-icon>
      {{states.weather.dark_sky.attributes.temperature }}°
  compact_mode: true
  hidden_tab_redirect: false
  hide_help: true
```

It doesn't appear to happen with either of these two configs:

No custom text for options menu
```
custom_header:
  compact_mode: true
  hidden_tab_redirect: false
  hide_help: true
```
Static custom text for options menu
```
custom_header:
  button_text:
    options: "Menu"
  compact_mode: true
  hidden_tab_redirect: false
  hide_help: true
```
So, it seems to be caused by having a template for the options menu text.
