### ISSUE TITLE
Default_tab and multiple lovelace dashboards from HA 0.107

### ISSUE THREAD

**Issue by acateon** [maykar/custom-header#157]
Dont know if this is a bug or if I'm having a hard time understanding the documentation but default_tab flag in exceptions dosent seem to respect the paths of the new way of handling multiple lovelace dashbaords.

Does CH only respect paths within a view as of now?

Pathing with the new multiple dashboards:
/lovelace-dashboard/home
/lovelace-mobile-dashboard/home
etc..

```
  exceptions:
    - conditions:
        user: Kiosk
      config:
        hide_help: true
        menu_dropdown: true
        kiosk_mode: true
        default_tab: lovelace-dashboard 
    - conditions:
        user_agent: Mobile
        media_query: "(max-width: 600px)"
      config:
        hide_help: true
        menu_dropdown: false
        kiosk_mode: true
        default_tab: lovelace-mobile-dashboard
```
