### ISSUE TITLE
Date Time does not show up in custom headere

### ISSUE THREAD

**Issue by dede34fr** [maykar/custom-header#158]
Hi,
I've got the custom_header config below, but no way to have date & time appear at the top of the screen ; anything wrong?
```
custom_header:
  locale: fr-FR
  header_text: '{{date}} - {{ hours24LZ }}:{{ minutesLZ }}'
  elements_color: darkblue
  menu_color: white
  shadow: true
  all_tabs_color: white
  tab_indicator_color: white
  compact_mode: true
  footer_mode: false
  hide_help: true
  menu_hide: false
  voice_hide: false
  options_hide: false
  menu_dropdown: false
  voice_dropdown: false
  reverse_button_direction: false
  chevrons: true
  indicator_top: false # Boolean	false	Places the current tab indicator on top of the tab
  default_tab: 0 #	number/string		The default starting tab when entering Lovelace
  reverse_tab_direction: false # Boolean	false	Places tabs at opposite side of the window in reverse order
  hide_tabs: "" # An array or comma separated string of tabs to hide, more info below
  hidden_tab_redirect: true # Boolean	true	Automatically redirects off hidden tabs to either the default tab or the first visible tab
  tab_icons: #	Set the icon of each tab, useful for templates, more info below
    - 0: mdi:home
    - 1: mdi:tools
    - 2: mdi:alarm-light-outline
    - 3: mdi:briefcase-outline
```
