### ISSUE TITLE
Odd spacing at top, cannot access raw editor

### ISSUE THREAD

**Issue by turbo4door** [maykar/custom-header#162]
Originally had installed CCH via HACS. Tried to remove and install CH, but am left with odd spacing below the header (as though it's not compact, though it actually is). The badges are spaced down too far eating up screen space. I also lose access to the raw configuration editor when I install CH. I'm runing 107.7. I was told by mayker to wait for a few days and try again. It has been over a week and the issue exists after installing it again.

I also am unable to remove CCH. When in HACS, it shows that it's still installed, but clicking on uninstall results in nothing, it is never removed.

current lovelace config looks like this:

```
background: null
custom_header:
  background: 'rgba(61, 61, 61, 1)'
  button_text: '{{ hours12 }}:{{ minutesLZ }} {{ ampm }}'
  compact_mode: true
  hidden_tab_redirect: false
  menu_hide: true
  disabled_mode: true
title: Home
views:
```
