### ISSUE TITLE
Got this error messages on my hass logs

### ISSUE THREAD

**Issue by ranrinc** [maykar/custom-header#165]
I got this error message and unsure what happen.. here are the details

Custom Header
```yaml
custom_header:
  editor_warnings: false
  exceptions:
    - conditions:
        user: b6cd68e3ae43460b9f19
      config:
        header_text: >-
          Milaxxx {{ time }} - {{ dayNameShort }}, {{ monthNameShort }} {{
          dayNum }}, {{ year4d }}
        hide_ch_settings: true
        hide_config: true
        hide_raw: true
        hide_tabs: '0,3,5,9'
        hide_unused: true
        options_hide: true
    - conditions:
        user: 6692dc57cd53476ebb76
      config:
        header_text: >-
          Luxxx {{ time }} - {{ dayNameShort }}, {{ monthNameShort }} {{ dayNum
          }}, {{ year4d }}
        hide_ch_settings: true
        hide_config: true
        hide_raw: true
        hide_tabs: '0,2,3,4,5,7,9'
        hide_unused: true
        options_hide: true
    - conditions:
        user: 348e2d58dba84ce794
      config:
        hide_tabs: '1,4,5'
  header_text: >-
    Ricxxxx {{ time }} - {{ dayNameShort }}, {{ monthNameShort }} {{ dayNum }},
    {{ year4d }}
```

Error Logs
```
/hacsfiles/custom-header/custom-header.js:603:7486 TypeError: t.header.menu.shadowRoot is null
/hacsfiles/custom-header/custom-header.js:603:7261 TypeError: o.menu is null
```

My Home Assistant Version: 0.108.3
Custom Header Version: 1.3.8 

Browser use: Firefox 75.0 (macOS Catalina)

Error from the browser: 
<img width="505" alt="Screen Shot 2020-04-11 at 12 44 25 PM" src="https://user-images.githubusercontent.com/15801696/79036474-c5429a80-7bf2-11ea-80d3-fc9541f0b9f2.png">
