### ISSUE TITLE
Not possible to leave Default tab empty (null) in GUI

### ISSUE THREAD

**Issue by BoneheadFraggle** [maykar/custom-header#175]
Thanks a lot for Custom Header. I just love it!

A small issue:
When using the GUI to configure an exception, it is not possible to leave the Default Tab empty. 
If you try to leave it empty, it is automatically filled with the value from the "main profile".
The issue isthat this combination seems to override the function "Hidden Redirect". 

Example:
In the general setting, I have enabled "Hidden Redirect" and "Default Tab = 10".
In my exception, I have disabled "Hidden Redirect" and left "Default Tab" empty (but in grayed out it uses the main profile value, "10"). 
Any attempt to access an URL redirects me to "10", the Default Tab.

I manually changed to ```default_tab: []``` in the raw config editor, se below. After that, it works as expected. Hidden Redirect then works for all profiles, except my exception user, where it lets me access an URL directly.

Suggestion: Give the possibility to have "null" in Default Tab also in the GUI.

Edit:
Home Assistant 0.108.6
Custom Header  1.3.8

Config:
```
custom_header:
  chevrons: false
  compact_mode: true
  default_tab: '10'
  disable_sidebar: true
  exceptions:
    - conditions:
        user: user01
      config:
        disable_sidebar: false
        hide_config: false
        hide_header: false
        hide_raw: false
        hide_unused: false
        menu_hide: false
        options_hide: false
        show_tabs: []
        hidden_tab_redirect: false
        default_tab: []
    - conditions:
        user: user02
      config:
        default_tab: '0'
        hide_header: false
        show_tabs: '0,1,3,4,5,6'
    - conditions:
        user: MC02
      config:
        default_tab: '13'
        kiosk_mode: true
        show_tabs: '13'
    - conditions:
        user: 's6,s7,z3'
      config:
        default_tab: '14'
        show_tabs: '10,14'
  hide_config: true
  hide_header: true
  hide_help: true
  hide_raw: true
  hide_unused: true
  menu_hide: true
  options_hide: true
  show_tabs: '10'
  voice_hide: true
  hidden_tab_redirect: true
```

Thanks!
