### ISSUE TITLE
Compact Header went to the bottom of the page and duplicated

### ISSUE THREAD

**Issue by jhbcosta** [maykar/custom-header#177]
Hi.

After 0.109 my Compact Header went to the BOTTOM OF THE PAGE and DUPLICATED.

![image](https://user-images.githubusercontent.com/51212559/80729112-2668da00-8ade-11ea-9db9-308079c656da.png)

Thanks,
Jose.

**Comment by rpitera** [comment]
I have the same issue, but only when I change the font family of the header text.   If I remove that styling and reload resources, everything looks great again.

It doesn't matter whether I use header_text_css: or if I use a span style in header_text: - either one produces the results seen in the image above.

**Comment by rpitera** [comment]
Please reopen; here's my information.   My apologies for not including them in my reply.

CCH Version - 1.3.8
HomeAssistant - 0.109.6
Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)

No errors in Dev Tools.

Error in HA log:

```
Logger: frontend.js.latest.202004272
Source: components/system_log/__init__.py:209
First occurred: 10:13:37 AM (6 occurrences)
Last logged: 10:17:11 AM

https://MyURL/lovelace/0:0:0 ResizeObserver loop limit exceeded
https://MyURL/hacsfiles/custom-header/custom-header.js:603:26806 Uncaught TypeError: Assignment to constant variable.
```


Config:
```
## CUSTOM HEADER CONFIG
custom_header:
  compact_mode: false
  background: transparent
  header_text_css: 'font-family: "bordaw00-regular", san serif;'
  active_tab_color: cyan 
  notify_dot_color: '#FFFF00'
  options_color: 'gainsboro'
  header_text: >-
    <span style=color:gainsboro;margin-right:25px;>West of East</span>
    <button style=color:white;background:blue;font-size:.80em;margin-right:15px;padding:2px;border-radius:10px;>
    {{ states.sensor.washer_var.state }}</button>
    <button style=color:yellow;background:red;font-size:.80em;margin-right:15px;padding:2px;border-radius:10px;>
    {{ states.sensor.dryer_var.state }}</button>
    <button style=color:white;background:blue;font-size:.80em;margin-right:15px;padding:2px;border-radius:10px;>
    {{ states.sensor.mailbox_var.state }}</button>
    <button style=color:yellow;background:green;font-size:.80em;margin-right:15px;padding:2px;border-radius:10px;>
    {{ states.sensor.update_var.state }}</button> 
  button_text: 
    options: >-
      {{ states.sensor.header_var.state }} :: {{ date }} :: <ha-icon icon='mdi:weather-{{ states.weather.dark_sky.state }}'></ha-icon> {{ states.weather.dark_sky.attributes.temperature }}°F 
  exceptions:
    - conditions:
        media_query: "(min-width: 900px)" # For Desktop Only
      config:      
        hide_tabs:
          - 1
          - 3
          - 5
          - 7
          - 9
          - 11
          - 14
          - 18
    - conditions:
        media_query: "(max-width: 900px)" # For Mobile Only
      config:
        compact_mode: true
        hide_header: false
        button_text: 
          options: >-
            {{ states.sensor.header_var.state }}
        hide_tabs: 
          - 0
          - 2
          - 4
          - 6
          - 8
          - 10
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 23
          - 24
          - 25
```

If I remove/comment out the header_text: line, everything works fine again after a resource reload.

**Comment by GeorgeSG** [comment]
I'm having the same problem, without the duplication.

```yaml
custom_header:
  compact_mode: true
  hide_config: true
  hide_help: true
  hide_unused: true
  hide_reload_resources: true
  indicator_top: true
```

**Comment by lights0123** [comment]
After upgrading to 0.110.0, for me it switches to the bottom of the view after switching to a non-Lovelace tab and then back (e.g. starting in Overview, switching to Configuration, and then back to Overview).
```yaml
custom_header:
  button_text:
    options: '{{ time }}'
  compact_mode: true
  exceptions:
    - conditions:
        media_query: '(max-width: 600px)'
      config:
        chevrons: false
        menu_hide: hide
        options_hide: true
        voice_hide: true
```
