### ISSUE TITLE
Default page not functioning. 

### ISSUE THREAD

**Issue by tomlut** [maykar/custom-header#18]
For my gardener I have set only one view visible (#9) , set that to the default page and enabled kisok mode. However when logging in using this user in a private browsing window view #0 is shown in kisok mode.

![Screenshot_2019-12-16 Home Assistant](https://user-images.githubusercontent.com/10679300/70893095-7d45a980-203e-11ea-9f1d-81ce07189522.png)

**Comment by tomlut** [comment]
Configuration:
```
custom_header:
  compact_mode: true
  voice_hide: true
  exceptions:
    - conditions:
        user: steve
      config:
        kiosk_mode: true
        disable_sidebar: true
        menu_hide: true
        options_hide: true
        hide_tabs: '0,1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22'
        default_tab: '9'
        show_tabs: '9'
    - conditions:
        user: Guest
      config:
        hide_tabs: '15,16,17,18,19,20,21,22'
        show_tabs: '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14'
        disable_sidebar: true
        menu_hide: true
        options_hide: true
resources:
  - type: module
    url: /community_plugin/custom-header/custom-header.js
```

**Comment by tomlut** [comment]
Browser with issue: Firefox 71.0 and Chrome 79.0.3945.7.

No relevant errors in the log.

**Comment by maykar** [comment]
Will have more time to look into this later today, but just looking at your config I would suggest using either only `hide_tabs` or only `show_tabs` as well as removing button hiding and sidebar disabling when using kiosk mode as those things aren't shown/enabled in kiosk mode. Not sure if it will help the current issue or not, but worth a try:

```
custom_header:
  compact_mode: true
  voice_hide: true
  exceptions:
    - conditions:
        user: steve
      config:
        kiosk_mode: true
        default_tab: '9'
        show_tabs: '9'
    - conditions:
        user: Guest
      config:
        hide_tabs: '15,16,17,18,19,20,21,22'
        disable_sidebar: true
        menu_hide: true
        options_hide: true
```
