### ISSUE TITLE
header disappears after a refresh of the page - HA 0.110

### ISSUE THREAD

**Issue by valderaplets** [maykar/custom-header#184]
Hi,
I noticed that if I refresh the page, the header disappears.
i got this error in HA : 

`2020-05-20 14:29:57 ERROR (MainThread) [frontend.js.latest.202005190] https://MYDOMAIN/local/custom-lovelace/custom-header/custom-header.js:1:16310 TypeError: o[e].querySelector(...) is null`

and from firefox : 

![image](https://user-images.githubusercontent.com/63161106/82446706-68ff5000-9aa7-11ea-8b81-76caceffbba3.png)

custom_header config : 

```
custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
```

I don't have it on the phone at all anymore. :disappointed:
