### ISSUE TITLE
TypeError: document.querySelector(...)

### ISSUE THREAD

**Issue by garyak** [maykar/custom-header#186]
Full error repeating every time home panel loads in the HA log:

`2020-05-20 16:13:47 ERROR (MainThread) [frontend.js.latest.202005190] http://hassnuc.local:8123/hacsfiles/custom-header/custom-header.js:596:28526 TypeError: document.querySelector(...).shadowRoot.querySelector(...).shadowRoot.querySelector(...) is null`

HA 110.0, CH 1.4.0, HACS 24.5, Firefox 75.0
config:

```
custom_header:
  chevrons: false
  compact_mode: true
  header_text: Home
  hide_help: true
  voice_hide: true
```
