### ISSUE TITLE
0.110 reports Cannot read property 'shadowRoot' of null

### ISSUE THREAD

**Issue by IanAdd** [maykar/custom-header#188]
Log shows:

http://homeassistant.local:8123/hacsfiles/custom-header/custom-header.js:596:7289 Uncaught TypeError: Cannot read property 'shadowRoot' of null

Using current version 1.4.1

**Comment by cjitariu** [comment]
Same issue here

**Comment by maykar** [comment]
Please provide the information requested from the bots comment above

**Comment by fermartv** [comment]
Same issue. Here are some details:
Ha version: 0.110.0
installation_type: Home Assistant Core on Docker
Custom header version: 1.4.1
Browser: Firefox 76.0.1

Custom header config:

```
resources:
  - type: module
    url: /hacsfiles/custom-header/custom-header.js


custom_header:
  compact_mode: true
  hide_help: true
  hide_config: true
  button_text:
    options: '{{ time }}'
```


HA log:
```
Logger: frontend.js.latest.202005190
Source: components/system_log/__init__.py:209
http://192.168.1.101:8123/hacsfiles/custom-header/custom-header.js:596:26508 TypeError: n.shadowRoot.querySelector(...) is null
```
