### ISSUE TITLE
ncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'

### ISSUE THREAD

**Issue by cjitariu** [maykar/custom-header#190]
Same issue here

Home Assistant 0.110.1
installation_type: Home Assistant Core on Docker
Custom header version: 1.4.1
Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
ERROR (MainThread) [frontend.js.latest.202005191] http://8123/hacsfiles/custom-header/custom-header.js:1:15255 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

```
resources:
  - type: module
    url: /hacsfiles/custom-header/custom-header.js

custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  button_text:
    options: '{{ date }} {{ hours24 }}:{{ minutesLZ }}'
  compact_mode: true
  swipe_animate: fade
  swipe_prevent_default: true
```
