### ISSUE TITLE
TypeError: e.voice is undefined

### ISSUE THREAD

**Issue by bkupidura** [maykar/custom-header#192]
Hey,
After upgrade to HA 0.110.1, custom-header stops working with:

```
2020-05-21 21:28:16 ERROR (MainThread) [frontend.js.latest.202005191] http://hostname/local/custom-header.js?v=1.4.3:1:15436 TypeError: e.voice is undefined
```
Error from web consolle:
```
TypeError: e.voice is undefinedcustom-header.js:1:15436
    buildHeader http://hostname/local/custom-header.js?v=1.4.3:1
    CustomHeader http://hostname/local/custom-header.js?v=1.4.3:1
    rebuild http://hostname/local/custom-header.js?v=1.4.3:596
    <anonymous> http://hostname/local/custom-header.js?v=1.4.3:596
    InnerModuleEvaluation self-hosted:1572
    evaluation self-hosted:1543
```

Web browser: Firefox 76.0.1 (64-bit)
Home-assistant version 0.110.1, running in docker.

Configuration:
```
resources:
  - url: /local/custom-header.js?v=1.4.3
    type: module
custom_header:
  compact_mode: true
  options_hide: true
  exceptions:
    - conditions:
        user: Guest
      config:
        disable_sidebar: true
        options_hide: true
        hide_tabs:
          - sensors
    - conditions:
        user: User1
      config:
        hide_tabs:
          - sensors
```
Custom header hash: af1406c25684c2f60c4348ab5c45336eda467ca7b6227b7716107ca3e79cf04a
