### ISSUE TITLE
Header disappears on HA 0.110.1

### ISSUE THREAD

**Issue by eliahru** [maykar/custom-header#193]
Following the updgrade of HA to version 0.110.1 I experience the problem with custom-header component causing the header disappear. When I reload the page, the header is visible for a particle of a second, then disappears leaving empty space.
Lovelace is in YAML mode, configuration part:
```
custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)  
  exceptions:
    - conditions:
        user: Corridor Wall
      config:
        hide_help: true
        hide_unused: true
        disable_sidebar: true
```

The log file contains the following error:
```
Logger: frontend.js.latest.202005191
Source: components/system_log/__init__.py:209
First occurred: 0:56:12 (17 occurrences)
Last logged: 1:02:23

http://MYIP:8123/hacsfiles/custom-header/custom-header.js:1:15444 Uncaught TypeError: Cannot read property 'setAttribute' of undefined
```
