### ISSUE TITLE
Fully Kiosk Browser

### ISSUE THREAD

**Issue by hugodelaroza** [maykar/custom-header#194]
Hi, I use custom header and it´s great!!

The problem is that when I open my dashboard in fully kiosk browser, the header remains standard. There is no change (in chrome it works fine)

Is there some special configuration for fully kiosk browser to work?

I just use this settings:

```
custom_header:
  exceptions:
    - conditions:
        user: Tablet
      config:
        compact_mode: true
        kiosk_mode: true
  voice_hide: true
```

Thanks a lot!
