### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by Majkeey** [maykar/custom-header#197]
**Config**
```
custom_header:
  background: 'rgba(150, 150, 150, 0.1)'
  chevrons: false
  exceptions:
    - conditions:
        user: Vb
      config:
        disable_sidebar: true
        hide_help: true
        hide_unused: true
        voice_dropdown: true
        hide_tabs: '7 to 10'
    - conditions:
        user: Vc
      config:
        disable_sidebar: true
        hide_help: true
        hide_unused: true
        voice_dropdown: true
        hide_tabs: '0 to 9'
        hidden_tab_redirect: true
        compact_mode: true
    - conditions:
        user: Xc
      config:
        hide_tabs: '0 to 9'
        hidden_tab_redirect: true
        compact_mode: true
    - conditions:
        user: Xy
      config:
        hide_tabs: '7 to 10'
```

**HA Logs**
Log Details (ERROR)
Logger: frontend.js.latest.202005191
Source: components/system_log/__init__.py:209
First occurred: 9:21:17 PM (2 occurrences)
Last logged: 9:25:51 PM

https://blahblah/local/custom-lovelace/custom-header/custom-header.js:1:7028 Uncaught TypeError: Cannot read property 'querySelector' of undefined
https://blahblah/local/custom-lovelace/custom-header/custom-header.js:1:11797 Uncaught TypeError: Cannot read property 'style' of null

**Chrome DevTools**
Uncaught TypeError: Cannot read property 'style' of null
    at buildButton (custom-header.js:1)
    at custom-header.js:1
    at custom-header.js:1

HA v0.110.1
Custom Header v1.4.5 - manual install
Chrome / HA Android app

I've searched opened and closed issues, HA forums etc. and nothing seems to work so far :/
I've tried:
* CH releases 1.3.9, 1.4.3, 1.4.5
* change all the 'iron-icon' entries to 'ha-icon'
* Replacing all (13) paper-icon-button with ha-icon-button
Restart after each change, nothing helped. All the version / changes were combined.

Any help would be appreciated, I might downgrade to HA 0.109 since that version was absolutely OK with CH.
