### ISSUE TITLE
Center Buttons

### ISSUE THREAD

**Issue by groft389** [maykar/custom-header#198]
Hey,

It is not directly a feature request or maybe it is I don't know if it is already possible with
workarounds.
Okay so you can invert the buttons to display it on the opposite Site with "reverse_button_direction".
Maybe do something like: "center_buttons" to display the buttons in the middle of the bar. 
It would be very useful as the tablet holder in my wall is blocking a little bit of both edges at the bottom so it is quite hard to press the corner buttons :/ 
Maybe this is already possible with CSS if so can you please someone tell me how ?

**Comment by maykar** [comment]
Centering the buttons is not something that I would add, but you can achieve something like it with a bit of trial and error. [Advanced styling docs.](https://maykar.github.io/custom-header/#styling/advanced)

```
custom_header:
  menu_css: 'margin-left: 50%;'
  options_css: 'margin-right: 50%;'
  voice_css: 'margin-right: 50%;'
```
