### ISSUE TITLE
Compact mode & only 1 view causes background gap at bottom of page

### ISSUE THREAD

**Issue by gbdavidx** [maykar/custom-header#201]
Please let me know how i need to resolve this!

```
custom_header:
# header_text: '{{ deviceID }}' # Must set compact_mode: false to display
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)

```
if i expand the sidebar it works fine, but i like to have it collapsed, https://imgur.com/a/xKclCyw the image doesnt expand to the whole screen
