### ISSUE TITLE
HA icon is larger after upgrade to 100.4

### ISSUE THREAD

**Issue by CarpeDiemRo** [maykar/custom-header#203]
![2020-05-31 10 59 24](https://user-images.githubusercontent.com/38489167/83347443-cd36d500-a32d-11ea-853b-10c952f0a962.jpg)

Code:
```
custom_header:
  active_tab_css: 'color: #eff5ff;'
  all_tabs_css: 'color: #d89729;'
  background: 'rgba(150, 150, 150, 0.2)'
  button_text:
    options: '<ha-icon icon= mdi:home ></ha-icon>  BigSister <br>{{ time }}'
  exceptions:
    - conditions: {}
      config: {}
  header_css: 'background: #2e4657; padding: 5px'
  header_text: smartHome
```

In 109.x the icon was displayed correctly

Tested on the following browsers: Chrome, Firefox
OS: macOS

Installation: HACS
Upgrade: HACS
