### ISSUE TITLE
Errors in relations to tabs

### ISSUE THREAD

**Issue by RogerSelwyn** [maykar/custom-header#205]
I keep getting the following errors in my logs.

I'm on HA 0.110.4 and CH 1.4.7, running on hassio on Ubuntu on parallels on Mac. I have two Dashboards configured via HA, though these errors don't seem to be generate very time I visit a dashboards so I'm not quite sure of the trigger. They seem to be being generated in groups of 10, but not always. My dashboards have 4 tabs on each dashboard.

```
Logger: frontend.js.latest.202005195
Source: components/system_log/__init__.py:209 
First occurred: 10:26:42 (51 occurrences) 
Last logged: 15:05:40

https://www.xxxxxxx.org.uk:8123/hacsfiles/custom-header/custom-header.js:596:20117 Uncaught TypeError: Cannot read property 'tabs' of undefined
https://www.xxxxxxx.org.uk:8123/hacsfiles/custom-header/custom-header.js:596:47165 TypeError: undefined is not an object (evaluating 'ha_elements().tabs')
```

**Comment by RogerSelwyn** [comment]
Added Custom Header config

```
custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  compact_mode: true
  default_tab: '0'
  disable_sidebar: true
  exceptions:
    - conditions:
        user: Roger Selwyn
      config:
        disable_sidebar: false
        hide_config: false
        hide_help: false
        hide_raw: false
        hide_unused: false
        options_hide: false
        show_tabs: []
```

No errors showing in browser console (I use Chrome/IOS HASS app), but then I don't know what makes it generate the errors, so getting the console to show errors maybe due to when it triggers errors in the logs.
