### ISSUE TITLE
CH errors caused by android HA Companion app

### ISSUE THREAD

**Issue by Pirol62** [maykar/custom-header#209]
Hi,

already updated to 110.4
HA on RASP3+ and HASSIo
CH 1.5.0 installed via HACS
````
Logger: frontend.js.latest.202005195
Source: components/system_log/__init__.py:209
First occurred: 9:08:42 (37 occurrences)
Last logged: 10:10:20

https://xxx.ui.nabu.casa/hacsfiles/custom-header/custom-header.js:596:15409 Uncaught TypeError: Cannot read property 'setAttribute' of null
https://xxx.duckdns.org:8123/hacsfiles/custom-header/custom-header.js:596:35592 Uncaught TypeError: Cannot read property 'partialPanel' of undefined
The issue is definately caused by Companion app.
The number of apperances is increasing during usage of that app
````
````
Logger: frontend.js.latest.202005195
Source: components/system_log/__init__.py:209
First occurred: 11:29:00 (21 occurrences)
Last logged: 13:41:00

https://xxx.ui.nabu.casa/hacsfiles/custom-header/custom-header.js:596:15409 Uncaught TypeError: Cannot read property 'setAttribute' of null
https://xxx.duckdns.org:8123/hacsfiles/custom-header/custom-header.js:596:35592 Uncaught TypeError: Cannot read property 'partialPanel' of undefined
````
Config:
````
custom_header:
  button_text:
    options: '{{ time }}'
  compact_mode: true
  exceptions:
    - conditions:
        user: Yvonne
      config:
        hide_tabs: '9'
    - conditions:
        user: Mobile
      config:
        default_tab: '0'
        disable_header: true
        hidden_tab_redirect: false
        hide_header: true
        shadow: false
  header_text: Zu Hause
  hide_header: true
  indicator_top: true
````
The browser cach was cleared
