### ISSUE TITLE
Error: "evaluating '_.voice.style'" 

### ISSUE THREAD

**Issue by poudenes** [maykar/custom-header#21]
Hi,

great add-on !! love it! 

I see some errors in log:

`2019-12-16 13:21:23 ERROR (MainThread) [frontend.js.latest.201911196] https://192.168.100.24:8123/community_plugin/custom-header/custom-header.js:576:42389 TypeError: undefined is not an object (evaluating '_.voice.style')`

already cleared cache etc...

**Comment by maykar** [comment]
Someone else reported this error and it turns out they were using some old CCH config in Custom Header's config. I can't tell for sure as you have not provided your config.

**Comment by lancer73** [comment]
Seeing this as well. Relevant part of the Lovelace config:

background: var(--background-image)
custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  compact_mode: true
  hide_help: true
  voice_hide: true
resources:
  - type: js
    url: /community_plugin/bar-card/bar-card.js
  - type: module
    url: /community_plugin/custom-header/custom-header.js
  - type: js
    url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js

(using iOS-dark-mode theme by the way)

From the log/javascript console:
https://xxx.xxx:8123/community_plugin/custom-header/custom-header.js:576:42389 TypeError: undefined is not an object (evaluating '_.voice.style')

Browser is Safari. (latest version)
HA version is 0.103

**Comment by maykar** [comment]
Thanks, looking into it now

**Comment by poudenes** [comment]
Here some more info

On all TABS at the left side exclude the Overview I get this error:
```
2019-12-16 18:40:47 ERROR (MainThread) [frontend.js.latest.201911196] https://192.168.100.24:8123/community_plugin/custom-header/custom-header.js:576:42389 TypeError: undefined
is not an object (evaluating '_.voice.style')
```

my Lovelace part:

```
custom_header:
  compact_mode: true
  editor_warnings: false
  exceptions:
    - conditions:
        user: tablet
      config:
        disable_sidebar: true
        header_text: Home Assistant
        hide_config: true
        hide_raw: true
        menu_dropdown: true
        menu_hide: true
        options_hide: true
        voice_dropdown: true
  header_text: Asingaborg
  hidden_tab_redirect: false
  hide_help: true
  hide_unused: true
  voice_hide: true
```
