### ISSUE TITLE
Custom Header not loading on iPad w/ iOS 10.3.3

### ISSUE THREAD

**Issue by coolguymatt** [maykar/custom-header#211]
Custom Header does not load on an old iPad I have. I cannot figure out if it should be able to run on it? I have done all the troubleshooting I can think of including wiping it completely.  Custom Header works great on all other devices.

I am running HA 0.110.4 with Custom Header 1.5 installed via HACS
iPad is iOS 10

user agent is Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1. 

Here is my custom_header config:

```
custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: Panel
      config:
        disable_sidebar: true
        hide_header: true
        hide_tabs: []
        show_tabs: '6'
  hidden_tab_redirect: false
  hide_tabs: '6'
```

**Comment by maykar** [comment]
Is this with the iOS companion app or Safari or both?

**Comment by maykar** [comment]
Is this an issue with just the Panel user or does CH not load even without that exception?

Also, a few fixes to your config. Not sure if it will make any difference, but there is no need to use both hide_tabs and show_tabs in one config and if you want to hide both the sidebar and header use kiosk_mode instead:

```
custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: Panel
      config:
        kiosk_mode: true
        show_tabs: '6'
        default_tab: '6' # This is occasionally necessary when only showing one tab
  hidden_tab_redirect: false
  hide_tabs: '6'
```
