### ISSUE TITLE
custom_header not found on my config

### ISSUE THREAD

**Issue by RWGaMeR** [maykar/custom-header#213]
Good Morning,
I inserted the custom header in my configuration for at least 2 months, a few days ago I updated the Home Assistant core, but now it doesn't work, how can I solve it?
I also tried to re-enter the configuration but nothing

my configuration:
```
custom_header:
  background: 'rgba(255, 152, 0, 0.01)'
  swipe_animate: fade
  swipe_prevent_default: true
  compact_mode: true
  button_icons:
    voice: mdi:microphone
    options: mdi:dots-vertical
```
version HA core: 0.110.4
installation: HACS
browser tested: chrome, firefox, safari, edge on Mac OS 10.15.5 and Windows 10

console browser error:
Uncaught (in promise) https://adressHomeAssistant/local/custom-header/custom-header.js?v=0.0.1
