### ISSUE TITLE
Header temporarily stops updating when screen turns off on Samsung device 

### ISSUE THREAD

**Issue by manuelo1983** [maykar/custom-header#225]
I have the custom header active in my Home Assistant and if i don't do anything on the tablet for a while, the time is not displayed currently. There is always a few minutes delay. Only if you keep the tablet on longer, the time will be updated correctly. I have a Samsaung T590 and have also disabled all battery saving options. Screen lock is also disabled. I can perform all other actions immediately after turning on the display without delay.

I have following settings:
- HassOS 4.10
- Home Assistant Core 0.111.1
- I use chrome as browser
- installed via HACS
- no error in logs

```
- custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  header_text: XXXXXXXX
  button_text:
    options: '{{ hours12 }}:{{ minutesLZ }}'
```

Greetings
