### ISSUE TITLE
Hide tabs not working

### ISSUE THREAD

**Issue by mar005** [maykar/custom-header#226]
I am having trouble with hide_tabs. I have the latest version of the plugin (1.5.8), and running the latest version of HA (0.111.2). This is my config. I am using all YAML mode and i have this below in the ui-lovelace file. It was always working, but I think after moving to 0.110 or 0.111 it stopped hiding my tabs. I like to hide the first tab. I have the following views below, but they are all commented out so it should be that on my iphone it hides home.yaml, and defaults to mobile_home.yaml.

```
custom_header:
  compact_mode: true
  menu: overflow
  exceptions:
    # - conditions:
    #     user: Miguel
    #   config:
    #     hide_tabs: '1 to 2'
    - conditions:
        user: Miguel
        user_agent: iPhone
      config:
        default_tab: 1
        hidden_tab_redirect: false
        hide_tabs: 0

title: Home
views:
- !include lovelace/views/home.yaml
#- !include lovelace/views/living_room.yaml
#- !include lovelace/views/bedroom.yaml
#- !include lovelace/views/office.yaml
- !include lovelace/views/mobile_home.yaml
- !include lovelace/views/mobile_climate.yaml
#- !include lovelace/views/mobile_remote.yaml
- !include lovelace/views/homelab.yaml
- !include lovelace/views/settings.yaml
```

**Comment by mar005** [comment]
Upon further testing i have noticed that my exception config is not picking up. So anything i put under conditions for Miguel and user_agent: iPhone is not picking up. I even changed it to Mobile.

**Comment by mar005** [comment]
So i removed everything to go down to this so i removed my user name and only left user_agent, and it seems that it works but only to hide the refresh, but it doesn't hide tab 0.


```
custom_header:
  compact_mode: true
  menu: overflow
  exceptions:
    - conditions:
        user_agent: iPhone
      config:
        hide_tabs: 0
        hide_refresh: true
        

title: Home
views:
- !include lovelace/views/home.yaml
- !include lovelace/views/mobile_home.yaml
- !include lovelace/views/mobile_climate.yaml
- !include lovelace/views/homelab.yaml
- !include lovelace/views/settings.yaml
```

**Comment by mar005** [comment]
OK figured it out. It only hides tabs, for me at least, based on view name.

```
custom_header:
  compact_mode: true
  menu: overflow
  exceptions:
    - conditions:
        user_agent: iPhone
      config:
        hide_tabs: home
        hide_refresh: true
        

title: Home
views:
- !include lovelace/views/home.yaml
- !include lovelace/views/mobile_home.yaml
- !include lovelace/views/mobile_climate.yaml
- !include lovelace/views/homelab.yaml
- !include lovelace/views/settings.yaml
```

**Comment by mar005** [comment]
Even further playing with this i see that the documentation seems to make no mention to support for view names when using default_tab as this worked for me. Yet still seems that the hide_tabs key doesn't work for me with numbers only works with names of views.

```
custom_header:
  compact_mode: true
  menu: overflow
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        default_tab: 1
        hide_tabs:
          - home
          - homelab
        hide_refresh: true
        

title: Home
views:
- !include lovelace/views/home.yaml
- !include lovelace/views/mobile_home.yaml
- !include lovelace/views/mobile_climate.yaml
- !include lovelace/views/homelab.yaml
- !include lovelace/views/settings.yaml
```

**Comment by mar005** [comment]
correction seems that the home assistant mobile app still doesn't display any of the changes I am doing, i was only able to fix this via my firefox browser by using inspector mode and switching the user agent.

**Comment by maykar** [comment]
Over the last few versions of the iOS app they changed the user agent to include no mention of device name, "mobile", etc. They are adding that back in (but not "mobile"). I believe this to be the source of all your issues.

**Comment by mar005** [comment]
I can close this now, as I noticed the forums: https://community.home-assistant.io/t/custom-header/155399/870?u=ha_fanatic

Also seems that now, for some reason, the hide_tabs accepts my numbers, i think it wasn't before.

**Comment by mar005** [comment]
> Over the last few versions of the iOS app they changed the user agent to include no mention of device name, "mobile", etc. They are adding that back in (but not "mobile") in the next releases. I believe this to be the source of all your issues.

Thanks! I think so, i did noticed a weird issue where numbers didn't work to hide tabs, but now it seems to work here.

```
custom_header:
  compact_mode: true
  menu: overflow
  exceptions:
    - conditions:
        user_agent: iOS
      config:
        default_tab: 1
        hide_tabs:
          - home
          - 3
        hide_refresh: true
        

title: Home
views:
- !include lovelace/views/home.yaml
- !include lovelace/views/mobile_home.yaml
- !include lovelace/views/mobile_climate.yaml
- !include lovelace/views/homelab.yaml
- !include lovelace/views/settings.yaml
```
