### ISSUE TITLE
Still errors with swipe navigation - Swipe does not work on mobiles

### ISSUE THREAD

**Issue by Pirol62** [maykar/custom-header#230]
HA Version 111.4
Swipe: 1.2.3
CH: 1.5.8
Rasp3+
Installed via HACS
CH-Config:
````
custom_header:
  button_text:
    options: '{{ time }}'
  compact_mode: true
  exceptions:
    - conditions:
        user: Yvonne
      config:
        hide_tabs: '9'
    - conditions:
        user: Mobile
      config:
        hidden_tab_redirect: false
        hide_header: true
        shadow: false
  header_text: Zu Hause
  hide_header: true
  indicator_top: true
````
Error:
````
https://xxx.duckdns.org:8123/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js:10:21 Uncaught TypeError: Cannot read property 'lovelace' of null
````
