### ISSUE TITLE
0.112.0 - Console errors, no UI menu, and sidebar stays

### ISSUE THREAD

**Issue by iderdik** [maykar/custom-header#231]
Home Assistant 0.112.0.dev20200617

custom-header 1.5.8  installed via HACS

Config in raw editor:
```
custom_header:
  exceptions:
    - conditions:
        query_string: embed
      config:
        disable_sidebar: true
        kiosk_mode: true
```

Error (using chrome on mac):
```
Logger: frontend.js.latest.202006130
Source: components/system_log/__init__.py:209
First occurred: June 22, 2020, 3:32:36 PM (32 occurrences)
Last logged: 11:56:25 AM

http://raspberrypi2.lan:8123/frontend_latest/chunk.402d6d994eeade1f37bb.js:2:61210 Uncaught YAMLException: unacceptable kind of an object to dump [object Undefined]
http://raspberrypi2.lan:8123/hacsfiles/custom-header/custom-header.js:1:17373 Uncaught TypeError: Cannot read property 'cloneNode' of null
https://ha.derdik.com/hacsfiles/custom-header/custom-header.js:1:17373 Uncaught TypeError: Cannot read property 'cloneNode' of null
http://raspberrypi2.lan:8123/config/lovelace/resources:0:0 Uncaught
https://ha.derdik.com/hacsfiles/custom-header/custom-header.js?cb=1:1:17373 Uncaught TypeError: Cannot read property 'cloneNode' of null
```
