### ISSUE TITLE
iOS - Footer Mode Not Sticking to Bottom of Screen

### ISSUE THREAD

**Issue by alexbussa** [maykar/custom-header#233]
**Issue**
After scrolling to the bottom of a view, when using `footer_mode: true`, the header will scroll up a bit rather than staying fixed to the bottom of the screen.

**Versions**

- Custom Header 1.6.x
- Home Assistant 0.111.4 – Docker

**Errors**

- None

**Reproducible in**
* Home Assistant for iOS (version 2020.2)
* Firefox for iOS (version 27.0) – Must be a view that scrolls

**Not reproducible in**
* Safari for iOS
* Chrome for iOS
* Mac desktop browsers

**Installation method**

- HACS

![IMG_9388](https://user-images.githubusercontent.com/938162/85803621-70e08e80-b6fc-11ea-8774-e0009f33c6c9.png)

**Comment by maykar** [comment]
If I understand this correctly, on iOS app and in Firefox the window is allowed to scroll past the bottom of the window causing the footer to follow. And this only happens when scrolling (as soon as you lift your finger it goes back to normal)?

**Comment by alexbussa** [comment]
It's not iOS rubber band effect where it bounces back. The footer follows and does not bounce back when you lift your finger.

I have thrown a background color on each of the containers Custom Header allows CSS to be applied to, but I haven't been able to find what is creating that extra space.

**Comment by maykar** [comment]
Could you share your CH config?

**Comment by alexbussa** [comment]
To rule out any external conflicts, I removed my theme and cut all lovelace configs down to the following. I'm still seeing the header not stick to the bottom of the screen.

**configuration.yaml**
```
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
```

**ui-lovelace.yaml**
```
title: Home Assistant
views:
  - icon: mdi:heart-pulse
    title: Health
    path: health
    cards:
      - !include lovelace/health/services.yaml
      - !include lovelace/health/battery.yaml
      - !include lovelace/health/zwave.yaml
  - icon: mdi:account-cog
    title: Preferences
    path: preferences
    cards:
      - !include lovelace/preferences/lights.yaml

custom_header: !include lovelace/plugins/custom_header.yaml
```
Included files are only using the entities type component.

**custom_header.yaml**
```
compact_mode: true
footer_mode: true
```
