### ISSUE TITLE
only the first "true" exception gets executed

### ISSUE THREAD

**Issue by basstp** [maykar/custom-header#234]
First of all, thank you for your great work!

**What I am trying to achieve is:**
The switch _weihnachtsmodus_ enables "christmas mode". When it is off, tab 1 should be hidden (it contains christmas light switches and so on).
On top of that, I want to hide most control elements and tabs 6 and 11 from my family (username: Familie), so they have a clean UI and cannot break things... ;)

**What I am experiencing is:**
When _switch.weihnachtsmodus_ is on, tab 1 is shown and my family sees a clean UI. All goes well. (only the second exception fires)
But as soon as I switch off _switch.weihnachtsmodus_, tab 1 gets hidden but suddently my family sees all the control elements and tabs 6 and 11. (only the first exception fires)

**It seems like only the first "true" (meaning the conditions are met) exception gets executed and after that, the following exceptions are discarded.**

I also tried switching the exceptions around with the same result: I can only get the first "true" exception to execute.

```
custom_header:
  exceptions:
    - conditions:
        template: '{{ states.switch.weihnachtsmodus.state  == "off" }}'
      config:
        hide_tabs: '1'
    - conditions:
        user: Familie
      config:
        disable_sidebar: true
        hide_ch_settings: true
        hide_config: true
        hide_help: true
        hide_raw: true
        hide_tabs: '6, 11'
        hide_unused: true
        menu_hide: true
        options_hide: true
  menu_hide: true
  restrict_users: true
  voice_hide: true
  chevrons: false
  compact_mode: true
```

Home Assistant 0.111.4
Custom Header 1.6.5; installed via HACS
affected Browsers; Chrome/Firefox (tested only these two)

Any help is much appreciated!

**Comment by maykar** [comment]
This is by design, exceptions are not combined. The exception with the most amount of true conditions is selected, in your case since they both have only one true condition it's a bit of a toss up. Do this instead:

```
custom_header:
  exceptions:
    - conditions:
        user: Familie
      config:
        disable_sidebar: true
        hide_ch_settings: true
        hide_config: true
        hide_help: true
        hide_raw: true
        hide_tabs: >-
          {% if is_state('switch.weihnachtsmodus', 'off') %}'1, 6, 11'
          {% else%}'6, 11'{%- endif %}
        hide_unused: true
        menu_hide: true
        options_hide: true
  menu_hide: true
  restrict_users: true
  voice_hide: true
  chevrons: false
  compact_mode: true
```

**Comment by maykar** [comment]
or even:

```
custom_header:
  exceptions:
    - conditions:
        user: Familie
      config:
        disable_sidebar: true
        hide_ch_settings: true
        hide_config: true
        hide_help: true
        hide_raw: true
        hide_tabs: >-
          {% if is_state('switch.weihnachtsmodus', 'off') %}'1, 6, 11'
          {% else%}'6, 11'{%- endif %}
        hide_unused: true
        menu_hide: true
        options_hide: true
  hide_tabs: "{% if is_state('switch.weihnachtsmodus', 'off') %}'1'{% else%}''{%- endif %}"
  menu_hide: true
  restrict_users: true
  voice_hide: true
  chevrons: false
  compact_mode: true
```

**Comment by maykar** [comment]
This could be clearer in the documentation and I'll be sure to add a note for it.

**Comment by basstp** [comment]
Wow that was quick, I guess your next coffee is on me. ;)

Thak you and keep up that great work!

**Comment by basstp** [comment]
Sorry for coming back to this, I sure thought your configuration would work. However, I am getting a very strange behavior:

**For user "Familie":**
When _switch.weihnachtsmodus_ is off, only tab 6 is hidden. When it is on, no tabs are hidden.

**For me:**
Nothing happens at all, all tabs are visible.

I have absolutely no clue what is going on. The templates make perfect sense and render correctly in Home Assistant's template dev-tool.

**Comment by maykar** [comment]
Yup, unnecessary quotes. Sorry bout that. Edited my comment as to not confuse others.

**Comment by maykar** [comment]
You should totally get rid of those unneeded options to make it cleaner :smile:

Many thanks for the coffee!

```
custom_header:
  exceptions:
    - conditions:
        user: Familie
      config:
        options_hide: true
        disable_sidebar: true
        hide_tabs: >-
          {% if is_state('switch.weihnachtsmodus', 'off') %}1, 6, 11
          {% else %}6, 11{% endif %}
  hide_tabs: "{% if is_state('switch.weihnachtsmodus', 'off') %}1{% else %}{% endif %}"
  menu_hide: true
  restrict_users: true
  voice_hide: true
  chevrons: false
  compact_mode: true
```
