### ISSUE TITLE
Allow naming and/or notes sections for each of the "exceptions" made in CH

### ISSUE THREAD

**Issue by ha14937** [maykar/custom-header#239]
Maybe it's just me - but using the Device ID to identify a devices exception/custom settings can become difficult when you have more than a few devices. I would love to see a field added to allow users to enter a "Device Name" (ex. _Kitchen Display_) that would be associated to the Device ID.

This would allow the list of Device IDs to be meaningful/descriptive strings, rather than nondescript alphanumeric strings.

**Comment by maykar** [comment]
DeviceID comes from [card-tools](https://github.com/thomasloven/card-tools#card-toolssrcdeviceid) and it is storing an identifier into the devices cache. It is a random string as there is no other unique identifier that is provided by Lovelace.

If you're logging in under the same account on these devices there is just no way to identify which device is being used. Essentially it boils down to: Where would the "Device Name" come from?

The easiest solution would be to create a user for the device and add an user exception. You could use the user agent of the device as well, but if you have multiple devices with the same user agent then their config would have to be the same.

**Comment by maykar** [comment]
Closing for now as I don't think this is currently possible.

**Comment by maykar** [comment]
Upon rereading the request, I may have missed the point of this. It sounds like you just want a way to differentiate the IDs in the code to keep track of what's what. Normally I'd suggest just making a comment in the YAML, but unfortunately, unless you're using YAML mode, HA removes comments. Though, if your looking for this type of control YAML mode might be something worth looking into.

Another way to accomplish this would be to use [custom variables](https://maykar.github.io/custom-header/#templates/custom). So you could do something like this:

```
custom_header:
  template_variables: '{% set kitchen_display = "put_the_device_id_here" %}'
  exceptions:
    - conditions:
        template: {{ deviceID  == kitchen_display }}
      config:
        hide_help: true
```

**Comment by ha14937** [comment]
Thanks for taking the time to write out the template_variable method - I'll work on that. Mostly I am seeking a better way to identify the exceptions I've made in the CH UI. (Perhaps I should have framed my question around "exceptions" rather than device IDs - but most of my exceptions are simply device IDs :)

In your original response, you had asked "_Where would the "Device Name" come from?_" **I am proposing letting the user give a set of exceptions a friendly name when they create a new exception for a device**. So, when they look at their list of exceptions in the CH UI, they see a list of more useful terms than device ID's, etc

Here is a screenshot of mine, with some "friendly name" labels that, if I were able to customize the name of a an exception, I would rather see in this list. 
![image](https://user-images.githubusercontent.com/56581105/86941602-20acf780-c112-11ea-9461-a42ac8f42408.png)


Anyway, appreciate your time - hope I explained myself better this time!

**Comment by maykar** [comment]
Ah, okay yeah, now I get what you're after. I will think about the best way to do this. Though, if you use template variables like the example above it does help a bit:

![image](https://user-images.githubusercontent.com/25127328/86943520-8ac69c00-c114-11ea-95a0-1ed4c36a3e8b.png)

**Comment by maykar** [comment]
You could even shorten it a bit more by doing something like this:

```
custom_header:
  template_variables: >-
    {% set kitchen_display = deviceID == "put_the_device_id_here" %}
    {% set different_device = deviceID == "put_the_device_id_here" and user == "Kevin" %}
  exceptions:
    - conditions:
        template: '{{ kitchen_display }}'
      config:
        hide_help: true
    - conditions:
        template: '{{ different_device }}'
      config:
        compact_mode: true
```

Then it would display as just `{{ kitchen_display }}` or `{{ different_device }}`
