### ISSUE TITLE
Uncaught ReferenceError: header is not defined

### ISSUE THREAD

**Issue by jo-me** [maykar/custom-header#241]
Hi,

I'm seeing these in the log all the time:

```
Protokolldetails ( ERROR )
Logger: frontend.js.latest.202007021
Source: components/system_log/__init__.py:209
First occurred: 10:54:03 (47 occurrences)
Last logged: 12:26:03

https://hostname:8123/hacsfiles/custom-header/custom-header.js:617:8350 Uncaught ReferenceError: header is not defined
```

Header seems to work though. Not sure which functionality is affected by that error mesasge.

Any idea what is causing this?

I'm running latest custom-header 1.6.7 (via HACS) on latest Home Assistant 0.112.4.

Config:
```
custom_header:
  button_text:
    menu: menu
    options: '{{ time }}<br>{{ date }}'
    voice: voice<br>button
  compact_mode: true
  hide_help: true
  restrict_users: true
  voice_hide: true
```
