### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by liamstears** [maykar/custom-header#242]
Getting an error in my logs that I hope can be resolved, I am new to HassOS so hope this isn't just user error

The error I'm getting is:
`/hacsfiles/custom-header/custom-header.js:1:12929 Uncaught TypeError: Cannot read property 'hass' of null`

Here is my header config:

```
custom_header:
  compact_mode: true
  disable_sidebar: true
  exceptions:
    - conditions:
        user: Liam
      config:
        chevrons: false
        compact_mode: false
        disable_sidebar: false
        hidden_tab_redirect: false
        hide_ch_settings: false
        hide_config: false
        hide_help: false
        hide_raw: false
        hide_unused: false
        menu_hide: false
        options_hide: false
        shadow: false
        voice_hide: false
  hide_ch_settings: true
  hide_config: true
  hide_help: true
  hide_raw: true
  hide_unused: true
  menu_hide: true
  options_hide: true
  voice_hide: true
```

I'm running HassOS on a Pi4, 0.113.2 and installed 1.6.7 via HACS

I hope I have given all the information you need and hope you can help
