### ISSUE TITLE
Custom Header menu item keeps hiding?

### ISSUE THREAD

**Issue by fribse** [maykar/custom-header#247]
HA  0.113.3
CH: 1.6.9
I've set up two users to not have it shown for, but normally it is set to be shown.
But I keep loosing the menu item, despite that I'm not logged in as one of the two users.
It's intermittent, not every time, but most times.
If I reinstall the CH, then it shows up, until I save it for the first time, then it's gone again.
Tested in both Firefox an Chrome, 
It's installed via HACS.

F12 doesn't give any errors

Custom header config:

```
custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: 'Adrian, Nathalie'
      config:
        disable_sidebar: true
        hide_config: true
        hide_raw: true
        hide_unused: true
        options_hide: true
    - conditions:
        user: alarmpanel
      config: {}
  header_text: Fribert Home
  voice_hide: true
```
