### ISSUE TITLE
can't see header text in compact mode

### ISSUE THREAD

**Issue by ktownsend-personal** [maykar/custom-header#248]
This thing is really nice! 
Unfortunately I can't seem to find a way to show the header text when in compact mode unless I enable split mode, but I don't want split mode. Is it possible?

**Comment by maykar** [comment]
One of the main things that makes compact mode compact is the fact that the header text is removed.

**Comment by ktownsend-personal** [comment]
Interesting. In my case there is more than enough width available for both the header text and the tabs in the same row, so it didn't occur to me that was by design to hide the header text in compact mode. Maybe that could be a future option?

**Comment by maykar** [comment]
Why not just use what you would have in the header text as the text for a tab or put the header text in a button's text like the option button?

You could even make a fake tab by adding an empty lovelace view where ever you'd like the text to be and then make it unclickable:

```
custom_header:
  tab_text:
    name_of_the_fake_view: 'Whatever text you want'
  tabs_css:
    name_of_the_fake_view: 'pointer-events: none;'

**Comment by maykar** [comment]
![image](https://user-images.githubusercontent.com/25127328/90271493-e7128f00-de29-11ea-9768-855ce50a4ac0.png)

If you want it to be the first tab then you should also make the default tab the next tab over and you can even remove the auto capitalization with `text-transform:capitalize;`:

```
custom_header:
  default_tab: 1
  tab_text:
    name_of_the_fake_view: 'Whatever text you want'
  tabs_css:
    name_of_the_fake_view: 'pointer-events: none; text-transform:capitalize;'
```
