### ISSUE TITLE
Header missing after updating to 1.7.1: Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by syphernl** [maykar/custom-header#254]
After updating to 1.7.1 my header disappeared. I briefly see it on loading the page but it then disappears.
In 1.7.0 and before the header shows fine. 

My config:

```yaml
custom_header:
  compact_mode: true
  hide_help: true
  hide_unused: true
  hide_config: true
  voice_hide: true
  chevrons: false
  hidden_tab_redirect: false
  button_text:
    options: >-
      {{ hours24LZ }}:{{ minutesLZ }} - {{state_attr('weather.buienradar','temperature') }}°c
  exceptions:
    - conditions:
        media_query: "(max-width: 600px)"
      config:
        options_hide: true
```

The browser console shows an uncaught typerror:

```
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
    at custom-header.js:146
    at custom-header.js:146
    at Array.forEach (<anonymous>)
    at conditionalConfig (custom-header.js:146)
    at Function.buildConfig (custom-header.js:146)
    at rebuild (custom-header.js:146)
    at custom-header.js:146
```

* Installed via HACS
* Chrome on Windows / Chrome on Android
* HASS 0.114.3
