### ISSUE TITLE
Side menu not hidden on kiosk mode

### ISSUE THREAD

**Issue by dmatik** [maykar/custom-header#255]
Hi,
Seems that after latest update 1.7.1 the side bar is not hidden on kiosk mode. 
I use kiosk mode being triggered by query.

```

custom_header:
  kiosk_mode: false
  exceptions:
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true

```
