### ISSUE TITLE
Footer mode does not stretch iframe card to bottom of screen

### ISSUE THREAD

**Issue by blhoward2** [maykar/custom-header#258]
When displaying a website in a full-screen iframe, using compact mode and footer mode, the iframe draws to where it would if compact mode was not on and the space was left blank. When footer mode is not on the card correctly fills the screen. When compact mode is turned off everything looks as it should. Verified in both Chrome and Fully Kiosk Browser. Using the latest stable home assistant and the latest custom-header.

Raw configuration:

```
custom_header:
  compact_mode: true
  disable_sidebar: true
  exceptions: []
  shadow: false
  footer_mode: true
views:
  - background-image: center / cover no-repeat fixed url('/local/blue-abstract.jpg')
    badges: []
    cards:
      - aspect_ratio: 50%
        style: |
          ha-card {
            height: 100%
            width: 100%
          }
        type: iframe
        url: 'http://192.169.0.123/'
    icon: 'mdi:home-outline'
    panel: true

```

![Screen Shot 2020-08-27 at 11 51 45 PM](https://user-images.githubusercontent.com/33612110/91519377-75722080-e8c0-11ea-892e-02c62fd0277f.png)
