### ISSUE TITLE
hide_ch_settings: true | not working

### ISSUE THREAD

**Issue by Murder3D** [maykar/custom-header#259]
Hello,

I would like to report that the function:

hide_ch_settings: **true** does not work.

If I set it to true I am able to access the Custom Header options when I click on the Lovelace options button (three vertical dots, top right corner) as well as if I set it to false.

I've tested this on:

my PC (Using Chrome 84.0.4147.135 official build)
iPhone 11 (using the Home Assistant app v0.114.4)
Amazon Fire HD 8 tablet (using Fully Kiosk Browser v1.39.3-fire)

Custom Header (v1.7.5) was installed via HACS (v1.5.2) and both are updated to the latest version as of today September 2nd, 2020

I am using the following configuration:

```
custom_header:
  exceptions:
    - conditions:
        user: Amazon Fire HD 8
      config:
        compact_mode: true
        disable_sidebar: true
        hide_ch_settings: true
        hide_config: true
        hide_help: true
        hide_raw: true
        hide_unused: true
        menu_dropdown: false
        menu_hide: true
        options_hide: false
        reverse_button_direction: false
        voice_dropdown: false
        voice_hide: true
        reverse_tab_direction: false
```

I am not finding any error messages regarding CH on HA log file.

I am sorry if this has already been reported.

Thank you
![CH](https://user-images.githubusercontent.com/68924586/92021407-ffefcf80-ed59-11ea-8a34-ce218997412a.jpg)
