### ISSUE TITLE
Not able to "hide_tabs" by title if title contains spaces

### ISSUE THREAD

**Issue by finity69x2** [maykar/custom-header#262]
trying to set "hide_tabs" for tab by title doesn't work if the tab title contains spaces in it.

code example that won't work:

lovelace_views/lovelace_garage_view.yaml

```
title: Garage Power
cards:
  - type: entities
    title: Garage Power strip
    show_header_toggle: false
    state_color: true
    entities:
.
.
.
```

ui-lovelace.yaml

```
custom_header:
  compact_mode: true
  hide_config: true
  hide_raw: true
  hide_help: true
  voice_hide: true
  chevrons: false
  hide_tabs: >-
    {{ 'Alerts, ' if states.sensor.nws_alerts_are_active.state == "off" and states.input_boolean.show_nws_test_alerts_view.state == "off" else '' }}
    {{ 'Tank, ' if states.input_boolean.show_tank_view.state == "off" else '' }}
    {{ 'Garage Power, ' if states.input_boolean.show_garage_power_view.state == "off" else '' }}
.
.
.
views:
  - !include '/config/lovelace_views/lovelace_garage_view.yaml'
```

in the example the "Garage Power" view won't hide.
