### ISSUE TITLE
Header Doesn't Always Load

### ISSUE THREAD

**Issue by apop880** [maykar/custom-header#264]
Recently, I've been having an issue where custom header won't load. The regular Home Assistant header loads without being compact or styled. This doesn't seem to be happening in the mobile app, only in Chrome on Windows 10. I've tried clearing cache without success as well. Here's the error I get in Chrome Dev Tools:

```
Uncaught TypeError: Cannot read property 'hass' of null
    at getHass (custom-header.js:1)
    at custom-header.js:1
```

I'm on the 1.7.7 release of Custom Header, installed through HACS and configured in YAML mode. I'm on .115 of Home Assistant but saw the same on .114 as well. Here's my YAML configuration for Custom Header:

```
custom_header:
  background: 'rgba(51,51,51,0.6)'
  compact_mode: true
  voice_hide: true
  chevrons: false
  exceptions:
    - conditions:
        user: redacted
      config:
        kiosk_mode: true
        show_tabs: '7,8'
    - conditions:
        user_agent: Android
      config:
        menu_hide: true
        options_hide: true
        hide_tabs: '7,8'
    - conditions:
        user: redacted
        user_agent: Android
      config:
        menu_hide: true
        options_hide: true
        hide_tabs: '6,7,8'
```

Refreshing the browser reliably causes the header to properly load.
