### ISSUE TITLE
Space below panel view in 0.116.0 beta

### ISSUE THREAD

**Issue by matt8707** [maykar/custom-header#269]
It seems that in HA 0.116.0 beta, custom-header adds space below the view in kiosk mode. When I remove the query string, and the header and sidebar shows, the space is not there.

![view](https://user-images.githubusercontent.com/36163594/94985866-510e0180-055a-11eb-9b4e-02e96ec773af.jpg)

```yaml
custom_header:
  exceptions:
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true
```

**Errors:** none
**Home Assistant:** 0.116.0b1
**Custom Header:** 1.8.3
**Browsers:** Safari, Chrome, Firefox
**Installation method:** HACS
**Lovelace Mode:** YAML
