### ISSUE TITLE
CH always redirects to tab 0

### ISSUE THREAD

**Issue by noxhirsch** [maykar/custom-header#27]
The new Custom Header redirects always to tab 0 even if no default is set. In the editor I can see a 0 in default_tab but can't remove it (it always reappears).
This is my config:
```
custom_header:
  chevrons: false
  compact_mode: true
  editor_warnings: false
  hide_help: true
  menu_hide: true
  voice_hide: true
  hidden_tab_redirect: false
  hide_tabs: 'floorplan, feed'
```

Thank you for help!

EDIT:
- I'm using HA 103.0, CA 1.0.1 & up2date Chrome on Win10
- No relevant errors in Console & Log
