### ISSUE TITLE
Installed, then what?

### ISSUE THREAD

**Issue by Fishairman90** [maykar/custom-header#271]
I am running HA version 0.115.4 and trying to install customer-header 1.8.3

Followed the instructions on installing the "integration" via HACS. Clicked install. It then says:

When you add this to your lovelace configuration use this

 url: /hacsfiles/custom-header/custom-header.js
 type: module

Im using the UI mode in Lovelace so I go to edit dashboard/raw  config editor and pate the code it tells you to. So for example my first few lines of the Lovelace raw config show this:

Then I Reboot...

Nothing happens...

Don't have a way to open the custom-header menu editor or anything. 

```
url: /hacsfiles/custom-header/custom-header.js
type: module
views:
  - title: Whole Picture
    path: whole_picture
    icon: 'mdi:home'
    panel: false
    badges: []
    cards:
      - type: weather-forecast
        entity: weather.home
      - type: entities
        entities:
          - sensor.us_coronavirus_confirmed
          - sensor.us_coronavirus_current
          - sensor.us_coronavirus_deaths
          - sensor.us_coronavirus_recovered
        title: United States Covid
```
