### ISSUE TITLE
Bad performance with customElements

### ISSUE THREAD

**Issue by zibous** [maykar/custom-header#272]
When I activate the custom header, the constructor of a customElements is called multiple times. This worsens the display of the view massively.

**System Home Assistant 0.116.0b5**
Frontend-Version: 20201001.1 - latest
arch | x86_64
-- | --
dev | false
docker | false
hassio | false
installation_type | Home Assistant Core
os_name | Linux
os_version | 5.4.0-48-generic
python_version | 3.8.2
timezone | Europe/Vaduz
version | 0.116.0b5
virtualenv | true

![Bildschirmfoto 2020-10-07 um 20 03 12](https://user-images.githubusercontent.com/30198737/95369811-3af49e00-08d8-11eb-9411-b4dfa6cb7bb9.png)

**Config**
```yaml
## ########################################
## Compact Custom Header
## ########################################

custom_header:
  compact_mode: true
  header_text: "IPS Smarthome"
  footer_mode: false
  hide_help: true
  background: "rgba(0,0,0,0.8)"
```

Without custom_header:
![Bildschirmfoto 2020-10-07 um 19 50 09](https://user-images.githubusercontent.com/30198737/95369297-8eb2b780-08d7-11eb-91ef-dea6d1115661.png)

With custom_header:
![Bildschirmfoto 2020-10-07 um 19 52 22](https://user-images.githubusercontent.com/30198737/95369346-9d996a00-08d7-11eb-99ef-d34e7bd82f93.png)

customElement:
```
class ContentCardExample extends HTMLElement {
	
	constructor() {
		super();
		console.log('*****Event - card - constructor', Math.random().toString(36).substr(2, 9), new Date().getTime());
	}
	
    set hass(hass) {
		if (!this.content) {
            let startTime = new Date()
            console.log("Create new ha-card", startTime)
			const card = document.createElement("ha-card");
			card.header = "Example card";
			this.content = document.createElement("div");
			this.content.style.padding = "0 16px 16px";
			card.appendChild(this.content);
			this.appendChild(card);
		}

		const entityId = this.config.entity;
		const state = hass.states[entityId];
		const stateStr = state ? state.state : "unavailable";

		this.content.innerHTML = `
        The state of ${entityId} is ${stateStr}!
        <br><br>
        <img src="http://via.placeholder.com/350x150">
      `;
	}

	setConfig(config) {
		if (!config.entity) {
			throw new Error("You need to define an entity");
		}
		this.config = config;
	}

	// The height of your card. Home Assistant uses this to automatically
	// distribute all cards over the available columns.
	getCardSize() {
		return 3;
	}
}

customElements.define("content-card-example", ContentCardExample);

```
Is there a workaround for so I can use the CCH?
