### ISSUE TITLE
Sidebar is resized with compact_mode: false

### ISSUE THREAD

**Issue by ThePicklenat0r** [maykar/custom-header#29]
When `compact_mode` is set to `false` the side bar is still resized as if it were set to `true`. It is really apparent when on other panels:

![image](https://user-images.githubusercontent.com/9081070/70933553-3047e000-200a-11ea-9a2a-d103a3833c33.png)

Example config:

```
custom_header:
  hide_tabs: '5'
  hide_unused: true
  hide_config: true
  compact_mode: false
  hide_help: true
```
