### ISSUE TITLE
iOS app - default tab not highlighted

### ISSUE THREAD

**Issue by VDRainer** [maykar/custom-header#30]
First, @maykar, Thanks for the new Custom Header! 

HA 0.103.0, CH 1.0.2
If i reload the ios app, the following error is raised in the log:
```
2019-12-16 22:00:47 ERROR (MainThread) [frontend.js.latest.201912041] http://192.168.77.67:8123/community_plugin/custom-header/custom-header.js:576:41723 TypeError: undefined is not an object (evaluating 'e.button_text.menu')
```
The default tap is opened and i see a gap between the header and the first buttons.
![Auswahl_233](https://user-images.githubusercontent.com/26381449/70943768-e71b7e80-2051-11ea-9d57-894ea716965d.png)
also the Home (tab 0) icon ist active, but the default tab should be tab 13.
![Auswahl_234](https://user-images.githubusercontent.com/26381449/70943892-306bce00-2052-11ea-97c7-dae9eacc1849.png)
Sometimes the LL refresh message comes up and the gap goes away, but still doesn't show the default tab activated.
![Auswahl_235](https://user-images.githubusercontent.com/26381449/70944438-5a71c000-2053-11ea-8161-fea907c3c36e.png)

Exception for Mobile:
```
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        compact_mode: true
        options_hide: true
        chevrons: false
        default_tab: tpad_baustelle 
        background: var(--primary-background-color)
        active_tab_color: var(--primary-color)
```

**Comment by maykar** [comment]
Try the latest release and see if it helps and let me know. I'll have to charge up all my test iOS devices tonight as there seems to be some more issues centered around iOS.

**Comment by VDRainer** [comment]
Thanks @maykar , the gap is fixed, no error anymore in  log.
Still an issue with the default tab. It opened, but CH does not show the active tab button as in my first screenshot.

**Comment by maykar** [comment]
Progress! 😄 Keep this issue open and I'll just change the title.

**Comment by maykar** [comment]
Going to mark this as a duplicate since this seems to be an issue outside of iOS and someone created an issue just for it.

https://github.com/maykar/custom-header/issues/43

**Comment by VDRainer** [comment]
Sorry @maykar , but i still have this issue.
Maybe i explained it bad.
I reload the iOS app, the default view (13) opens, but the header shows 0 - 4 with 0 highlighted, like in my first screenshot, without the gap now.
Now if i want to open a view near 13, i first have to scroll the header 3 times to the left to open it.
The tab text and indicator are active, but the header does not 'jump' to it.

**Comment by maykar** [comment]
I understand the issue. The default tab is opened but it is not highlighted nor is it in the centered in the page. Still working on it, that's why I haven't closed #43

**Comment by maykar** [comment]
Try the latest version v1.0.9 as it tries to address this issue

**Comment by VDRainer** [comment]
Sorry @maykar , still an issue. :confused:
Did some testing and used numbered icons for this
CH 1.1.0
![Auswahl_237](https://user-images.githubusercontent.com/26381449/71238144-a8acea80-2303-11ea-9c4d-ed79a7f93703.png)
This is the default_tab (10) in FF on my desktop.
``` 
   - conditions:
        user: Rainer
      config:
        default_tab: tpad_home 
        background: var(--ha-card-background)
        active_tab_color: var(--primary-color)
        menu_hide: true
        hide_config: true
        hide_help: true```
```
**Now on to the iOS app.**
Reloading app, default_tab on mobile (12) opens, header shows:
![Auswahl_238](https://user-images.githubusercontent.com/26381449/71238567-b9119500-2304-11ea-9305-87ced1a8c574.png)
scrolling the header to the left:
![Auswahl_239](https://user-images.githubusercontent.com/26381449/71238794-49e87080-2305-11ea-8b32-324f2fb88ed1.png)
after a few seconds, the header jumps back to the position after reloading.

Now if i tap the views from 0 to 15, it works from 0 to 8.
After tap on 9, the header jumps back
![Auswahl_240](https://user-images.githubusercontent.com/26381449/71239531-0ee73c80-2307-11ea-8618-232837ebbe7d.png)
and does this until number 15
![Auswahl_241](https://user-images.githubusercontent.com/26381449/71239665-638ab780-2307-11ea-8946-fbc408618980.png)

This is really confusing.
