### ISSUE TITLE
view_css does not apply in kiosk mode

### ISSUE THREAD

**Issue by noxhirsch** [maykar/custom-header#34]
Hi,
it seems like view_css does not apply in kiosk mode:
```
custom_header:
  chevrons: false
  compact_mode: true
  editor_warnings: false
  hidden_tab_redirect: false
  hide_help: true
  hide_tabs: 'floorplan, feed'
  menu_hide: true
  voice_hide: true
  view_css: 'margin-top: -200px!important;'
```
In "normal mode" the style is applied. In kiosk mode it doesn't change anything.

HA 0.103.0, CH 1.0.3, Chrome up2date on Win 10
No errors in log & console
