### ISSUE TITLE
Viewport resize (padding, margin)

### ISSUE THREAD

**Issue by ercsey** [maykar/custom-header#35]
Using custom-header with fully kiosk browser and Google Chrome. Regardless of the background image or page content the page does not fit to screen. Same page with compact-custom-header and same config worked without any issue. It's like with hiding the header it does not decrease the viewports height (I don't know if I've explained correctly)
- Home Assistant 0.103.0
- Custom Header: 1.0.3
- Fully Kiosk browser, Google Chrome Version 79.0.3945.79 (Official Build) (64-bit)

Custom Header config:
```
custom_header:
  compact_mode: true
  kiosk_mode: true
  disable_sidebar: false
  hide_header: true
  default_tab: 1
  hide_tabs: 
    - 0
    - 2
  hide_help: true
  hide_unused: true
  hide_refresh: true
  hide_config: true
  hide_raw: true
  menu_hide: true
  voice_hide: true
  options_hide: true
```

Another thing is that with the following config it does not hide the header.
```
custom_header:
  compact_mode: true
  kiosk_mode: true
  disable_sidebar: true
  hide_header: true
```
Changing the ```disable_sidebar: true``` to ```false``` it hides the header too.

**Comment by maykar** [comment]
Try the latest release and I've modified both of your config examples to do what you want without unnecessary options.

First one. This one it looks like you wanted to keep the sidebar, but just remove header. That's what hide_header is for and since the header is hidden all the other config values are not needed:
```
custom_header:
  hide_header: true
  default_tab: 1
  hide_tabs: 
    - 0
    - 2
```

Second one. Kiosk mode hides header and sidebar so those options, as well as compact mode, are not needed:
```
custom_header:
  kiosk_mode: true
```
