### ISSUE TITLE
lit-element.js.map does not exist

### ISSUE THREAD

**Issue by ercsey** [maykar/custom-header#36]
Home Assistant 0.103.0
Custom Header: 1.0.3
Fully Kiosk browser, Google Chrome Version 79.0.3945.79 (Official Build) (64-bit)
Custom Header config:
```
custom_header:
  kiosk_mode: false
  disable_sidebar: false
  hide_header: false
  hide_help: false
  hide_unused: false
  hide_refresh: false
  hide_config: false
  hide_raw: false
  menu_hide: false
  voice_hide: true
  options_hide: false
  default_tab: 0
```
In Home Assistant developer-tools/logs I get this error:
```
"Tried to serve up '/config/www/community/custom-header/lit-element.js.map' but it does not exist"
```
