### ISSUE TITLE
In kiosk mode menu not disappear menu

### ISSUE THREAD

**Issue by ricain59** [maykar/custom-header#37]
![Screenshot_1](https://user-images.githubusercontent.com/13002652/70999401-44a2e000-20d1-11ea-93c1-36c226e6dbcb.png)
Hi,

I've this configuration for user "tablet":
```
custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: Tablet
      config:
        default_tab: '10'
        disable_sidebar: true
        header_text: casa
        hide_config: true
        hide_raw: true
        hide_tabs: '0,1,2,3,4,5,6,7,8,9,11'
        options_hide: true
        hide_header: true
        chevrons: false
        kiosk_mode: true
  header_text: Casa
  hide_help: true
  hide_unused: true
  voice_hide: true
```

With option kiosk mode, the bar menu should disappear?

**Comment by maykar** [comment]
Is this still an issue if you use:

```
custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: Tablet
      config:
        default_tab: 10
        kiosk_mode: true
  header_text: Casa
  hide_help: true
  hide_unused: true
  voice_hide: true
```

Everything else is unnecessary as kiosk_mode hides the header and sidebar
