### ISSUE TITLE
In kiosk mode the webpage is pushed up 

### ISSUE THREAD

**Issue by zeular** [maykar/custom-header#38]
Hi, when I use kiosk mode, the web page is pushed up so 10% of page is not visible. I'm using Chrome.
This is what my code looks like:

```
custom_header:
  compact_mode: true
  footer_mode: false
  hide_help: true 
  background: "#434954" 
  voice_hide: true
  exceptions:
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true
```

https://pastebin.com/Am1tQM9b

Edit:
From the log:
`Tried to serve up '/config/www/community/custom-header/lit-element.js.map' but it does not exist`
