### ISSUE TITLE
Kiosk mode cuts off the top of the Picture Element Panel

### ISSUE THREAD

**Issue by roblamoreaux** [maykar/custom-header#39]
I just moved from Compact Custom header to Custom header, and found kiosk mode broke.
I have my default view set to a picture element and in kiosk mode the top section of my picture element is cut off by about the distance of the normal header. I tried this on two different browsers. 
Hass.io Version 192, HassOS 2.12 and Custom Header 1.0.3
The config is;
```
custom_header:
  clock_date: true
  compact_mode: true
  exceptions:
    - conditions:
        user: 'Danielle, Camille, Abi, Colin'
      config:
        clock_format: '12'
        hide_tabs: ' 4, 5,6'
        menu: show
        notifications: show
        swipe_amount: '15'
        swipe_animate: none
        voice: show
        locale: []
    - conditions:
        user: House
      config:
        clock_format: '12'
        default_tab: '0'
        hide_tabs: '4,5,6'
        kiosk_mode: true
        menu: show
        notifications: show
        swipe_amount: '15'
        swipe_animate: none
        voice: show
        locale: []
  button_text:
    options: '{{ time }}<br>{{ date }}'
  swipe: true
resources:
  - type: module
    url: /community_plugin/custom-header/custom-header.js
```
