### ISSUE TITLE
Tabs not cover all header space

### ISSUE THREAD

**Issue by snakuzzo** [maykar/custom-header#41]
I'm on Chrome 79.0.3945.79
custom-header 1.0.6
homeassistant 0.103.0

This is how lovelace appears with custom-header

![image](https://user-images.githubusercontent.com/7205371/71045902-ef99b500-2136-11ea-8790-8e3efff2e81e.png)

...and this is how lovelace appears without custom-header...

![image](https://user-images.githubusercontent.com/7205371/71046036-5c14b400-2137-11ea-9005-0f7dcf32d915.png)

As you can see, on the right there is a lot of space unused using custom-header

![image](https://user-images.githubusercontent.com/7205371/71045981-2ff93300-2137-11ea-94a4-c2c8503d9646.png)

This is my configuration

```
custom_header:
  exceptions:
    - conditions:
        user: anna
      config:
        default_tab: anna
        disable_sidebar: true
        hide_config: true
        hide_help: true
        hide_raw: true
        hide_unused: true
        show_tabs: 'anna,clima,finestre'
        voice_hide: true
```
