### ISSUE TITLE
without  >- in template.....No way to get out of Kiosk mode

### ISSUE THREAD

**Issue by Mariusthvdb** [maykar/custom-header#42]
Have 4 modes in my setup:

```
input_select:
  mode:
    name: Mode selection
    icon: mdi:account-settings
    options:
     - Normal
     - Full house
     - Kiosk
     - Developer
#    initial: Normal
```

never used the Kiosk mode before, so all this input_select does is change the Theme state, to indicate the Kiosk mode is truly on.

Trying the feature on CH now with this:

```
kiosk_mode: >
  {{ is_state('input_select.mode','Kiosk') }}
```

enables the Kiosk mode just fine, really nice.

selecting one of the other modes after that, does make the input_select change state, and all other things belonging to that particular state.

It doesn't however stop the Kiosk mode! No way to get out of that, other than using the disable_ch suffix...

config:
```
#https://maykar.github.io/custom-header/#configuration/main
#header_text:

## all default
#disabled_mode: false
kiosk_mode: >
  {{ is_state('input_select.mode','Kiosk') }}

compact_mode: true

#footer_mode: true
#disable_sidebar: false
#hide_header: false
#hide_help: false
#hide_unused: false
#hide_refresh: false
hide_config: true
#hide_raw: false

# https://maykar.github.io/custom-header/#configuration/buttons
#menu_hide: false
#voice_hide: false
#options_hide: false
#menu_dropdown: false
#voice_dropdown: false
#reverse_button_direction: false
#button_icons:

button_text:
  options: >-
    {{ hours24 }}:{{ minutesLZ }} - {{state_attr('weather.home_darksky','temperature') }}°
#
#    {{ hours12 }}:{{ minutesLZ }} {{ AMPM }} -  <ha-icon icon={{states('sensor.weather_icon')}}></ha-icon>
#    {{state_attr('weather.home_darksky','temperature') }}°

show_tabs: >
  {% if not is_state('input_select.mode','Developer') %}0 to 21, 26 to 28
  {% else %} 0 to 28
  {% endif %}

# https://maykar.github.io/custom-header/#configuration/exceptions
exceptions:
  - conditions:
      user: Gezin, redacted
    config:
      show_tabs: 0 to 3,6,15 to 18
      voice_hide: true
      options_hide: true
  - conditions:
      user_agent: iPhone
    config:
      menu_hide: true
#      voice_hide: false
      options_hide: hide
  - conditions:
      user_agent: iPad
    config:
      menu_hide: true
#      voice_hide: false
      options_hide: hide

# https://maykar.github.io/custom-header/#configuration/tabs
#chevrons: true
#indicator_top: false
#default_tab:
#reverse_tab_direction: false
#hide_tabs: An array or comma separated string of tabs to hide, more info below
#show_tabs: An array or comma separated string of tabs to hide, more info below
#hidden_tab_redirect: true

tab_icons:
  alarm: >-
    {{states('sensor.alarm_panel_icon')}}
  phones_tablets: >-
    {{states('sensor.presence_icon')}}
  weer_klimaat: >-
    {{states('sensor.weather_icon')}}
  alarmclock: >-
    {{'mdi:alarm-off' if is_state('sensor.next_alarm','Not set') else 'mdi:alarm'}}

tabs_color:
  phones_tablets: >-
    {{state_attr('sensor.family_home','icon_color')}}
```

CH 1.0.6 HA 103.0

just tested it with this template:
```
kiosk_mode: >-
  {{ states('input_select.mode') == 'Kiosk'}}
```
and that does work alright, as does this: 
```
kiosk_mode: "{{ states('input_select.mode') =='Kiosk'}}"
```

and:
```
kiosk_mode: >-
  {{ is_state('input_select.mode','Kiosk') }}
```

will  add 'format templates needs >-' to title

can close this, and maybe set a general issue for the template specifics? Its a bit of a guess right now, since as you can see in my config, not all templates (see tabs_color and show_tabs) need the >- for multiline
