### ISSUE TITLE
active tab indicator doesn't follow

### ISSUE THREAD

**Issue by Mariusthvdb** [maykar/custom-header#43]
when going to the left panel developer tools, do some work and go back to overview, the home page is loaded. However the active tab indicator of CH is still on the tab one was before clicking developer tools.

![Schermafbeelding 2019-12-18 om 11 28 35](https://user-images.githubusercontent.com/33354141/71078506-d706ba80-2189-11ea-97b8-b2c97a6eb6e0.jpg)

this is on my Homepage, and should of course look like
![Schermafbeelding 2019-12-18 om 11 31 17](https://user-images.githubusercontent.com/33354141/71078573-f271c580-2189-11ea-8f80-45eda14dacec.jpg)

I ve also tried to reload the page, but that makes the indicator disappear altogether..

![Schermafbeelding 2019-12-18 om 11 34 02](https://user-images.githubusercontent.com/33354141/71078812-657b3c00-218a-11ea-99e2-c2dec628ad03.jpg)

HA 103.0 CH 1.0.6

CH config:
```
#https://maykar.github.io/custom-header/#configuration/main
#header_text:

## all default
#disabled_mode: false
kiosk_mode: >-
  {{ is_state('input_select.mode','Kiosk') }}

#"{{ states('input_select.mode') =='Kiosk'}}"

compact_mode: true

#footer_mode: true
#disable_sidebar: false
#hide_header: false
#hide_help: false
#hide_unused: false
#hide_refresh: false
hide_config: true
#hide_raw: false

# https://maykar.github.io/custom-header/#configuration/buttons
#menu_hide: false
#voice_hide: false
#options_hide: false
#menu_dropdown: false
#voice_dropdown: false
#reverse_button_direction: false
#button_icons:

button_text:
  options: >-
    {{ hours24 }}:{{ minutesLZ }} - {{state_attr('weather.home_darksky','temperature') }}°
#
#    {{ hours12 }}:{{ minutesLZ }} {{ AMPM }} -  <ha-icon icon={{states('sensor.weather_icon')}}></ha-icon>
#    {{state_attr('weather.home_darksky','temperature') }}°

show_tabs: >
  {% if not is_state('input_select.mode','Developer') %}0 to 21, 26 to 28
  {% else %} 0 to 28
  {% endif %}

# https://maykar.github.io/custom-header/#configuration/exceptions
exceptions:
  - conditions:
      user: Gezin, Hanna, Louise, Frederike, Marte, Wijke
    config:
      show_tabs: 0 to 3,6,15 to 18
      voice_hide: true
      options_hide: true
  - conditions:
      user_agent: iPhone
    config:
      menu_hide: true
#      voice_hide: false
      options_hide: hide
  - conditions:
      user_agent: iPad
    config:
      menu_hide: true
#      voice_hide: false
      options_hide: hide

# https://maykar.github.io/custom-header/#configuration/tabs
#chevrons: true
#indicator_top: false
#default_tab:
#reverse_tab_direction: false
#hide_tabs: An array or comma separated string of tabs to hide, more info below
#show_tabs: An array or comma separated string of tabs to hide, more info below
#hidden_tab_redirect: true

tab_icons:
  alarm: >-
    {{states('sensor.alarm_panel_icon')}}
  phones_tablets: >-
    {{states('sensor.presence_icon')}}
  weer_klimaat: >-
    {{states('sensor.weather_icon')}}
  alarmclock: >-
    {{'mdi:alarm-off' if is_state('sensor.next_alarm','Not set') else 'mdi:alarm'}}

tabs_color:
  phones_tablets: >-
    {{state_attr('sensor.family_home','icon_color')}}
```

**Comment by Mariusthvdb** [comment]
please reopen, this is still the case. Just posted on that https://community.home-assistant.io/t/custom-header/155399/148?u=mariusthvdb

**Comment by maykar** [comment]
I have a possible fix coming in the next release, hang tight.

**Comment by maykar** [comment]
Try the latest version v1.0.9 as it tries to address this issue

**Comment by Mariusthvdb** [comment]
really sorry, but no, installed 1.1.0, and the issue is still there Safari, Mac. Chrome Mac seems to do alright though!

thing is, clicking the Overview takes the browser to `https://mydomain.etc.etc:8123/Lovelace` which is the same page as `https://mydomain.etc.etc:8123/Lovelace/home`

Maybe that is confusing things? It is on Safari... Just so you know, Ive tested this also on a ingocnito browser so no blockers or whatever plugins loaded.

Moreover, I have a few badges on several pages with a tap navigation action taking me to another tab, eg like this:

```
  - type: state-label
    entity: sensor.levering_of_verbruik
    tap_action:
      action: navigate
      navigation_path: /lovelace/home_energy
```

and although the page navigates as it should, the active tab indicator stays put yet again....

And also, this is on Safari. Chrome is behaving just fine.
