### ISSUE TITLE
header too big

### ISSUE THREAD

**Issue by ljmerza** [maykar/custom-header#45]
If I hard refresh, the header loads fine but if I just refresh after that, the header is really long. Seems like A timing issue. A margin-top: 111px and padding: 8px is making the header big and icons out of line

![image](https://user-images.githubusercontent.com/4085765/71116459-37095b00-21a2-11ea-9894-78461615df84.png)

version 1.0.7

```
custom_header:
  compact_mode: true
  hide_help: true
  hide_unused: true
```
