### ISSUE TITLE
Header overlap on iOS 12

### ISSUE THREAD

**Issue by deluxestyle** [maykar/custom-header#46]
On my iPad mini 2 the Header is overlapping the views and the first tap is not visible

![IMG_0003](https://user-images.githubusercontent.com/662779/71119227-fcbbb000-21d9-11ea-8821-74bcd21409a7.jpeg)

My config
```
custom_header:
  compact_mode: true
  hide_config: true
  chevrons: false
```

Hass.io Version 0.103.0
