### ISSUE TITLE
exceptions config does not appear to work

### ISSUE THREAD

**Issue by kquinsland** [maykar/custom-header#50]
hi :).  Thank you for this wonderful bit of UI tweaking code!

I am attempting to get per-user layouts working... but can't seem to get it. Can you give me some pointers on where to look for clues?

Here's my config:

```
title: MyHA
resources:
  # HA has no support for per-user UI, so for now we use this wonderful component to make sure
  #   that we do get something that looks like a per-user UI
  # See: https://github.com/maykar/custom-header
  ##
  - url: /community_plugin/custom-header/custom-header.js
    type: module
    # A card that allows us to display big numbers; see: https://github.com/custom-cards/bignumber-card
  - url: /community_plugin/bignumber-card/bignumber-card.js
    type: js
    # A wonderful way to get related actions for an entity
    # See: https://github.com/custom-cards/button-entity-row
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: module

# See: https://maykar.github.io/custom-header/#configuration/main
custom_header:
  ###
  # DEFAULTS
  ###
  # Kiosk mode HIDES the header completely; i'd rather have it be small, but still on top.
  kiosk_mode: false
  compact_mode: true
  footer_mode: false
  # Hides the voice/assistant/chat button
  voice_hide: true
  # We create "exceptions" to the config for each user
  exceptions:
    - conditions:
        user: ME
      config:
        # When compact mode is ON, no header text, so use "footer mode" to test
        header_text: "hello ME "
        footer_mode: false
        options_hide: false

    - conditions:
        # There is a ?kds at the end of the URL...
        query_string: kds
        user: kds
        # TODO: ask the author which of these takes precedence; if user ME logs in but has ?kds at the end of the url, what happens?

      config:
        # We want the kds interface to be very limited and w/ very few ways to accidentally navigate away
        ##
        # Hides the options button ⚠️ ( the three dots on the topright)
        options_hide: true
        # Places menu button in the options drop-down
        menu_dropdown: true
        # Disables and hides the sidebar and menu button
        disable_sidebar: true
        # Hides the "Unused Entities" option in the options menu
        hide_unused: true
        # Hides the "Refresh" option in the options menu
        hide_refresh: true
        # Hides the "Configure UI" option in the options menu ⚠️
        hide_config: True
        # Hides the "Raw Config Editor" option in the options menu ⚠️
        hide_raw: true
        # Hides the "Help" option in the options menu
        hide_help: true
```

I am using version `Installed: 1.0.8` of your. plugin via HACS.
I am on home-assistant [`0.103.0`](https://github.com/home-assistant/home-assistant/issues/30060) and i am using both Firefox on OSX and Chromium on Raspbian to test. the `kds` user is the user on the raspbian host.

On both hosts, i see the same UI layout :(.

Also, what is the "order" for deciding which exceptions get applied?  See my `# TODO:` note above
