### ISSUE TITLE
Transparency not working for me on home/default view only

### ISSUE THREAD

**Issue by rpitera** [maykar/custom-header#51]
Using the latest version to date, 1.0.9.  Tried the following:

- background: transparent

- header_css: 'background-color: rgba(0,0,0,0.3)'
 
- header_css: 'background-color: transparent !important'

None of which worked for the default page - the other tabs/views work fine.  The only thing that **has** worked for me is:

`header_css: 'background: center / cover no-repeat url("/local/bg/hex.jpg") fixed'`

which works like the original CCH transparent option worked; unfortunately when I use this, none of my button texts work and instead of showing the variable values, it shows the config text.  (e.g. instead of the actual date and the state values, it displays "{{ date }} - {{ states.sensor.header_var.state }}".  _(Should note that I also tried reversing the single and double quotes in that line to see if it made a difference but it doesn't.  It's as if there's something in that line that needs to be escaped otherwise the rendered result breaks button text.)_

Additional info:

HA version - Hass.io 0.103.2  (YAML mode)
Browsers - Chrome and Firefox

CH config:

```
## CUSTOM HEADER CONFIG
custom_header:
  compact_mode: true
  background: transparent
  #header_css: 'background: center / cover no-repeat url("/local/bg/hex.jpg") fixed'
  #header_css: 'background-color: rgba(0,0,0,0.3)'
  #header_css: 'background-color: transparent !important'
  active_tab_color: cyan 
  notify_indicator_color: '#FFFF00'
  button_text:
    options: '{{ date }} - {{ states.sensor.header_var.state }}'
  exceptions:
    - conditions:
        media_query: "(max-width: 900px)"
      config:
        hide_tabs: 
          - 0
    - conditions:
        media_query: "(min-width: 900px)"
      config:
        hide_tabs:
          - 1
```
Not seeing any relevant errors in either HA logs or dev tools in Chrome.
