### ISSUE TITLE
Templates not rendering

### ISSUE THREAD

**Issue by Martinvdm** [maykar/custom-header#61]
Hi,

I searched the docs but cannot find it. How do your create this GIF, provided in the docs? An HA card with switches to set functions of Custom Header live.

![demo 1](https://user-images.githubusercontent.com/1952661/71320692-3416af00-24af-11ea-979c-f8b6d545641b.gif)

I did created some input_booleans in HA, but there seems no way to set the actions for the booleans. Perhaps this is not the right approach or templates are not rendered correctly.

thanks

**Comment by maykar** [comment]
This is actually from my development setup and I have a bunch of input_texts and input_booleans and then use config like this:
```
custom_header:
  header_text: '{{ states.input_text.header_text.state }}'
  kiosk_mode: '{{ states.input_boolean.kiosk_mode.state == "on" }}'
  compact_mode: '{{ states.input_boolean.compact_mode.state == "on" }}'
  footer_mode: '{{ states.input_boolean.footer_mode.state == "on" }}'
  tab_icons:
    pacman: '{% if states.input_boolean.icon_changes.state == "on" %}mdi:ghost{% endif %}'
    '1': '{% if states.input_boolean.icon_changes.state == "on" %}mdi:pac-man{% endif %}'
  button_icons:
    menu: '{% if states.input_boolean.icon_changes.state == "on" %}mdi:xbox-controller-menu{% endif %}'
    voice: '{% if states.input_boolean.icon_changes.state == "on" %}mdi:microphone-variant{%else%}mdi:comment-processing{% endif %}'
    options: '{% if states.input_boolean.icon_changes.state == "on" %}mdi:dots-horizontal{% endif %}'
  button_text:
    menu: '{% if states.input_boolean.text_changes.state == "on" %}Menu{% endif %}'
    options: '{% if states.input_boolean.text_changes.state == "on" %}{{dayNameLong}}<br>{{date}}{% endif %}'
  menu_dropdown: '{{ states.input_boolean.menu_dropdown.state == "on" }}'
  voice_dropdown: '{{ states.input_boolean.voice_dropdown.state == "on" }}'
  reverse_tab_direction: '{{ states.input_boolean.reverse_tab_direction.state == "on" }}'
  reverse_button_direction: '{{ states.input_boolean.reverse_button_direction.state == "on" }}'
```

**Comment by Martinvdm** [comment]
Thanks. I actually did made your example, but nothing happens, when changing the booleans or the text. How did you let Custom header react on the state changes?

**Comment by maykar** [comment]
Custom Header automatically makes the changes when the entities change. Did you make the input_booleans and input_texts in your configuration.yaml?

**Comment by maykar** [comment]
Might be helpful to share your config here and try `test_template` info here:

https://maykar.github.io/custom-header/#templates/templates

**Comment by Martinvdm** [comment]
Yep.
```
  ch_mode:
    name: Custom Header Mode
  ch_compact_mode:
    name: Custom Header Compact Mode
  ch_footer_mode:
    name: Custom Header Footer Mode
  ch_hide_voice_button:
    name: Custom Header Hide Voice Button
```
and
```
custom_header:
  header_text: '{{ states.input_text.ch_header_text.state }}'
  disabled_mode: '{{ states.input_boolean.ch_mode.state == "off" }}'
  compact_mode: '{{ states.input_boolean.ch_compact_mode.state == "on" }}'
  footer_mode: '{{ states.input_boolean.ch_footer_mode.state == "on" }}'
  background: repeat url("/local/img/header.png")
  voice_dropdown: '{{ states.input_boolean.ch_hide_voice_button.state == "on" }}'
```

**Comment by maykar** [comment]
Any errors in your logs? Check out the first reply to your question from the bot, go to that issues section and provide me with as much info from there as you can.

**Comment by Martinvdm** [comment]
test template output from f12:
```
Custom Header test returned: "{{ states.input_boolean.ch_mode.state == "off" }}"
```` 

custom header config:
```
custom_header:
  header_text: '{{ states.input_text.ch_header_text.state }}'
  disabled_mode: '{{ states.input_boolean.ch_mode.state == "off" }}'
  compact_mode: '{{ states.input_boolean.ch_compact_mode.state == "on" }}'
  footer_mode: '{{ states.input_boolean.ch_footer_mode.state == "on" }}'
  background: repeat url("/local/img/header.png")
  voice_dropdown: '{{ states.input_boolean.ch_hide_voice_button.state == "on" }}'
  test_template: '{{ states.input_boolean.ch_mode.state == "off" }}'
```
Errors in HA log: none

HA version: 103.0
Custom Header version: 1.1.3
Browser: Chrome (newest)

**Comment by maykar** [comment]
Since you're using `disabled_mode: '{{ states.input_boolean.ch_mode.state == "off" }}'` are you sure you're not just disabling Custom Header?

**Comment by Martinvdm** [comment]
I was thinking that, but when just give in: _disabled_mode: off_ i do see custom header enabled, but other booleans are not working either. e.g. i do see the background and when enabled the footer is active also in contrast the fact that the boolean is off, also compact_mode  does not function, footer_mode is not functioning, voice_dropdown is not functioning.

**Comment by maykar** [comment]
disabled_mode accepts true or false, not off. 

Just remove the whole `disabled_mode:` line and see what happens.

**Comment by Martinvdm** [comment]
tried it; it enabled ch instantly but no changes when activate/deactivate booleans like footer, compact voice etc.

**Comment by maykar** [comment]
And the test template still returns `Custom Header test returned: "{{ states.input_boolean.ch_mode.state == "off" }}"`?

Very strange, seems your system isn't rendering the templates at all.

**Comment by maykar** [comment]
Would you mind sharing your custom header config including your whole resources section?

**Comment by Martinvdm** [comment]
Yes it does look like what you are saying. tried playing with and without quotes, but is giving an error when using without quotes, the code seems legit to me but not accepted. In the Templates section of HA the template is accepted just fine.

```
title: Home Assistant
custom_header:
  header_text: '{{ states.input_text.ch_header_text.state }}'
  disabled_mode: false
  compact_mode: '{{ states.input_boolean.ch_compact_mode.state == "on" }}'
  footer_mode: '{{ states.input_boolean.ch_footer_mode.state == "on" }}'
  background: repeat url("/local/img/header.png")
  voice_dropdown: '{{ states.input_boolean.ch_hide_voice_button.state == "on" }}'
  test_template: '{{ states.input_boolean.ch_mode.state == "off" }}'
resources:
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: js
  - url: /community_plugin/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/config-template-card/config-template-card.js
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
```
