### ISSUE TITLE
default_tab & hide_tabs not working in exceptions

### ISSUE THREAD

**Issue by sheminasalam** [maykar/custom-header#68]
I have been using CCH with success both with mobile and desktop browsers. But with the latest CH plugin i am having issues hiding unwanted tabs and setting default tabs in my mobile browser. I am using full kiosk browser which worked perfectly with CCH. Now only partial CH controls are working like kiosk mode is working and other functioning in kiosk mode. Please check why default tabs and hide tabs are not working in mobile. It is working in desktop only.

**Comment by maykar** [comment]
Please, read the comment above and provide the required information for me to help identify your issue. I can confirm that Custom Header works just fine on multiple mobile systems including while using Fully Kiosk Browser. Without more information, I am unable to help you.

**Comment by sheminasalam** [comment]
CH config```custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: The Kiosk
      config:
        chevrons: false
        default_tab: '1'
        footer_mode: true
        hide_tabs: '2,7'
        kiosk_mode: true
  hide_tabs: '1,7'
  voice_hide: true```

I am running hassio 2.12 in orange pi PC. I am not able to find any relevant logs in hassio for CH. I am using Fully kiosk browser. I have tried to load CH in 3 mobile phones but all showed the same issue. Even when the kiosk mode was enabled, the hide tabs an default tabs were not in mobiles. but it was working fine in desktop browsers.

**Comment by maykar** [comment]
So all mobile phones are logged in as the user "The Kiosk"?

Are these iOS devices, Android devices, or anything else?

Are you using the latest version of Custom Header? Version 1.1.5

Also, why are you using footer_mode and hide_tabs while also using kiosk_mode? Kiosk mode hides the entire header/footer and sidebar so there would be no reason to hide those while using kiosk_mode.

**Comment by sheminasalam** [comment]
Mykar i am using the same user. I am using this in android device. The config is in this way because i was trying to find the solution by changing config. Since I have been CCH there was slide function in it. But with CH and default and hide tab issues I was trying different solutions.

**Comment by maykar** [comment]
Confirm that you are using Version 1.1.5 of custom header by pressing F12 on a PC browser like chrome and looking in the dev console. You should see this:

![image](https://user-images.githubusercontent.com/25127328/71454122-17070800-275d-11ea-9d33-802b4fc47856.png)

If you are using a lower version make sure you update, if you're having issues updating [try these instructions](https://github.com/maykar/custom-header/issues/65), and clear the cache in fully kiosk.

**Comment by sheminasalam** [comment]
yes it is v1.1.5

**Comment by maykar** [comment]
Have you cleared the Fully Kiosk cache?

I'm currently using your exact config only changing the username to my own, on 2 android devices and one iOS device, using fully kiosk on the android devices, and everything is working as intended.

Not sure what the issue could be

**Comment by maykar** [comment]
Going to create a user with a space in the user's name to see if that is the issue, but I seem to recall someone else using that just fine.

**Comment by sheminasalam** [comment]
cleared the cache..reinstalled the app and all...even used three phones to verify the issue. i am also wondering that as kiosk mode is working dine but why not default and hide tabs that too just in mobile. Can it be anything with my router. I have had strange issues with my router.

**Comment by maykar** [comment]
Wouldn't be anything with your router. Can you try using just chrome on those mobile devices to see if that works okay?

**Comment by sheminasalam** [comment]
i have tried and i get the same result. Kiosk mode is working without hide and default tabs settings.

**Comment by sheminasalam** [comment]
now i see that the default and hide tabs are not working with desktop browser too. This issue sis only with exception configuration, the hide tab is working fine with default user.

**Comment by maykar** [comment]
Could you try adding this to your main config and copy pasting the result from the dev console?
`test_template: '{{ user }}'`

**Comment by sheminasalam** [comment]
where do i have to copy this.
```
custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: rivana
      config:
        test_template: '{{ user }}'
        chevrons: false
        default_tab: '3'
        hide_tabs: '2,7'
        kiosk_mode: false
  hide_tabs: '1,7'
  voice_hide: true
```

or

```
custom_header:
  compact_mode: true
  test_template: '{{ user }}'
  exceptions:
    - conditions:
        user: rivana
      config:
        chevrons: false
        default_tab: '3'
        hide_tabs: '2,7'
        kiosk_mode: false
  hide_tabs: '1,7'
  voice_hide: true
```

**Comment by maykar** [comment]
Your second example would be fine

**Comment by sheminasalam** [comment]
have tried it and now i find that the default and hide tabs set for exceptions user are still not loading but the hide tabs of the main user is loading and default is completely different tab than mentioned for both the users. The developer console logs are

```
VM75 3:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
:8123/community_plugin/custom-header/custom-header.js:576   CUSTOM-HEADER    Version 1.1.5  
:8123/community_plugin/custom-header/custom-header.js:576 Custom Header test returned: "rivana"
```

**Comment by maykar** [comment]
Whenever you get a chance can you share your resources section of your lovelace config. About the only thing I can think of at this point is a conflicting add-on and that will give me a list so that I can install what you have and test.

**Comment by sheminasalam** [comment]
```
resources:
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - type: module
    url: /community_plugin/lovelace-layout-card/layout-card.js
  - type: js
    url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js
```

I reinstalled it from HACS and now it is working fine with desktop browser but in mobile the default and hide tabs are still not working.
