### ISSUE TITLE
bottom padding or extra space

### ISSUE THREAD

**Issue by bsodi** [maykar/custom-header#72]
hi,
please please help looked everywhere and been bugging me for the pass week now.  using custom header and i was able to do the top padding adjustment but now since updated to 103.5 the bottom is the issue.  i tried adjusting the bottom and it does make it bigger but not smaller.  Red is the background and using picture elements.  please please help.  using raspberry chrome kiosk.  screen is 1280,800 with touchscreen.  the red bottom shows on desktop and on tablets.  
Installed: 1.1.7
```
custom_header:
  compact_mode: true
  disabled_mode: false
  hide_help: true
  footer_mode: true
  exceptions:
    - conditions:
        user: Kiosk1
      config:
        default_tab: home_1280
        hide_tabs: 'Home_1200, home,'
        panel_view_css: 'padding-top:96px; padding-left:0px; padding-right:0px; padding-bottom:0px;'
        kiosk_mode: true
```
![screenshot-bottom over](https://user-images.githubusercontent.com/58150197/71624180-454a7480-2baf-11ea-958a-288e85fe1274.png)
