### ISSUE TITLE
Errors in log related to Split Mode

### ISSUE THREAD

**Issue by rccoleman** [maykar/custom-header#73]
I'm using v1.1.7 of custom_header and I'm periodically getting errors like this in my HA logs:
```
2019-12-31 08:16:20 ERROR (MainThread) [frontend.js.latest.201912041] https://xxx:8123/community_plugin/custom-header/custom-header.js:576:26048 Uncaught TypeError: Cannot read property 'split_mode' of undefined

2019-12-31 00:20:40 ERROR (MainThread) [frontend.js.latest.201912041] https://xxx/community_plugin/custom-header/custom-header.js:576:59286 TypeError: undefined is not an object (evaluating 't.split_mode')
```

Here's my custom_header config:
```
custom_header:
  compact_mode: true
  button_text:
    options: '{{ now().strftime("%-I:%M%p") }}<br>{{ now().strftime("%x") }}'
  hide_unused: true
  hide_config: true
  hide_help: true
  voice_hide: true
  split_mode: false
```

This happens whether or not I have `split_mode` enabled. I originally didn't have `split_mode` defined and was getting the errors above, but I just added it, forced a hard refresh in Chrome, and I immediately got the same error:

```
2019-12-31 08:36:27 ERROR (MainThread) [frontend.js.latest.201912041] https://xxx:8123/community_plugin/custom-header/custom-header.js:576:26048 Uncaught TypeError: Cannot read property 'split_mode' of undefined
```

Whenever I refresh the HA Lovelace page with the Chrome dev tools open, I get this in the console at the end:

<img width="637" alt="Screen Shot 2019-12-31 at 8 44 03 AM" src="https://user-images.githubusercontent.com/860888/71627922-3d3c0600-2baa-11ea-9f80-9de6fff5909a.png">

I did migrate from compact_custom_header as soon as custom_header became available, if that matters.  I'm running HA 0.103.5 installed via Hass.io, and I installed custom_header via HACS.  I'm using Lovelace in YAML mode and can provide more of my config if needed.  I do have a bunch of styled cards, but nothing too crazy.
