### ISSUE TITLE
Turning on Kiosk mode with swipe navigation stops hiding hidden tabs

### ISSUE THREAD

**Issue by Birdbrainuk** [maykar/custom-header#74]
I think the title says it all but here is what I know

Was setting up a new use exception for an echo show so it had limited pages and showed in kiosk.

When in this mode if i am using your swipe navigation as well then I can swipe to all of the hidden tabs.  If kiosk is turned off then it will not swipe to the hidden tabs.

I have tried this as the master configuration and as an exception and the results are the same  
 
Here is my config.  Just changing kiosk to on from this shows the issue.
```
custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: Show
      config:
        hide_tabs: '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14'
        default_tab: '15'
        menu_dropdown: true
        voice_dropdown: true
        options_hide: true
  hide_tabs: '0,15'
  default_tab: '1'
```

I have not seen any logs

Issue shows using firefox on the echo show and chrome on android but i suspect others as well.
