### ISSUE TITLE
Cannot get tab_icons to work

### ISSUE THREAD

**Issue by rumart** [maykar/custom-header#77]
I'm using a fresh install of ch, version 1.1.7 on HA 0.103.3

Other stuff works, like conditions, compact mode etc, but tab_icons generates an error in Dev Console

```
custom-header.js:576 Uncaught TypeError: Cannot set property 'icon' of null
    at styleHeader (custom-header.js:576)
    at processAndContinue (custom-header.js:576)
    at buildConfig (custom-header.js:576)
    at custom-header.js:576
```
The issue occurs even if I strip out all other config options for ch and use the example from the docs:

```
resources:
  - url: /local/atomic_calendar.js
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js?v=1.0.0
    type: js

custom_header:
  tab_icons:
    0: mdi:home

```
