### ISSUE TITLE
Show tabs in edit mode

### ISSUE THREAD

**Issue by noxhirsch** [maykar/custom-header#90]
Hi,
I'd love to have the option back from the old custom compact header to show all tabs in edit mode.
In the old version, this was possible with `edit_mode_show_tabs`
Thank you very much!

**Comment by maykar** [comment]
Custom header now just shows the original header and hides itself when in edit mode, meaning that no tabs should be hidden in edit mode as Custom Header should no longer be seen.

**Comment by maykar** [comment]
Sorry, this shouldn't happen and is most definitely a bug. While in edit mode, nothing should be hidden. Custom Header doesn't modify the existing header anymore, it instead makes a new header and hides the default one. Then in edit mode Custom Header hides and the default header is shown. Will look into it.

**Comment by noxhirsch** [comment]
Mh .. okay I can see that the header is getting big again, but the tabs stay away.
This is my config:
```
custom_header:
  chevrons: false
  compact_mode: true
  editor_warnings: false
  exceptions:
    - conditions:
        query_string: kiosk
      config:
        hide_tabs: []
        kiosk_mode: true
        view_css: 'top:-8px;'
    - conditions:
        query_string: k_feed
      config:
        active_tab_color: 'rgba(255,255,255,0.8)'
        all_tabs_color: 'rgba(255,255,255,0.6)'
        all_tabs_css: 'padding:0px 8.8px; height:40px;'
        header_css: 'background: rgb(26, 29, 38);padding:0 2px; height:43px;'
        hide_tabs: floorplan
        indicator_top: true
        options_hide: true
        stack_css: 'margin: 0;'
        tab_indicator_color: 'rgba(255,255,255,0.1)'
        view_css: 'top:-8px;'
    - conditions:
        user_agent: Mobile
      config:
        hide_tabs: []
        options_hide: true
  hidden_tab_redirect: false
  hide_help: true
  hide_tabs: 'floorplan, feed'
  menu_hide: true
  voice_hide: true
```
