### ISSUE TITLE
Android tablet not respecting CH settings

### ISSUE THREAD

**Issue by teknetia** [maykar/custom-header#93]
I have run into an issue where my Android wall display/tablet is not applying the CH configuration, even after a full clear of the browser cache. I am using Fully Kiosk Browser to load the HASS UI. It previously worked and I am a little unclear on what may have changed to cause an issue.

As far as I can see there aren't any errors in the logs and if I log in as the same user (wall-display) in Chrome/Brave/Safari it correctly loads the UI mods I expect. The issue also happens in the stock browser (Lightning).

## Info
Home Assistant 0.103.6 (via Hass.io)
Custom Header 1.1.7 (via HACS)
Fully Kiosk Browser 1.3.4

## Configuration
```
custom_header:
  chevrons: false
  exceptions:
    - conditions:
        user: 'Wall Display, wall-display'
      config:
        compact_mode: true
        disable_sidebar: true
        hide_config: true
        hide_help: true
        hide_raw: true
        hide_unused: true
        menu_hide: true
        voice_hide: true
        options_hide: true
  hidden_tab_redirect: false
  shadow: false
resources:
  - type: module
    url: /community_plugin/custom-header/custom-header.js
```
