### ISSUE TITLE
Exceptions condition by browser_mod deviceId

### ISSUE THREAD

**Issue by hwmland** [maykar/custom-header#97]
Would be nice to be able to use deviceId (or even better - alias) as condition filter. Something like:

```
custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        device: my_android_phone, 99980b13-dabc9563
      config:
        hide_help: true
        menu_dropdown: true
```
