### ISSUE TITLE
allow multiple words in user_agent exception

### ISSUE THREAD

**Issue by Mariusthvdb** [maykar/custom-header#99]
Hi,

please consider adding the possibilty to add multiple words in the user_agent exceptions. Use case:

need to be able to set a view based in both Chrome and Mac to be in user_agent. Chrome is also mobile, and that won't show the Cast interface. I need to be abe to select only desktop Chrome browser windows to show the tab.

please see
https://community.home-assistant.io/t/custom-header/155399/344?u=mariusthvdb

```
   - conditions:
        user_agent: Chrome Mac
```
would be the config I am looking for.
thanks!

**Comment by maykar** [comment]
This has been added or fixed in the [latest version 1.2.2](https://community.home-assistant.io/t/custom-header/155399/367). After updating be sure to check your browser's dev console (usually F12) to make sure you are running the latest version. If it doesn't display 1.2.2 you may either need to clear your cache or reinstall.

This would be implemented using the new `template:` condition in exceptions or just by using a template in other config that looks for words in the userAgent template var.

**Comment by Mariusthvdb** [comment]
thanks Ryan, will test asap.
please note the version is Master in the inspector now, not 1.2.2:

<img width="559" alt="Schermafbeelding 2020-01-22 om 18 12 12" src="https://user-images.githubusercontent.com/33354141/72916764-e3f76a80-3d42-11ea-8146-e0b2d03beb68.png">

**Comment by maykar** [comment]
Yeah, side effect of the failed build. If you reinstall it should display correctly

**Comment by Mariusthvdb** [comment]
> This would be implemented using the new template: condition in exceptions or just by using a template in other config that looks for words in the userAgent template var.

I am a bit confused by this. my current config with exceptions doesn't work as expected. can I post here, or do I need another issue for that?

it s just that using this main template:
```
show_tabs: >-
  {% if is_state('input_select.mode','Developer') %}0 to 29{% else %}0 to 3,5 to 22,27,29{% endif %}
```

works on desktop, but not anymore on mobile (iPhone)

I had these exceptions to add to the above:

```
exceptions:
  - conditions:
      user_agent: Chrome
    config:
      show_tabs: >-
        {% if is_state('input_select.mode','Developer') %}0 to 30{% else %}0 to 3,5 to 22,27,29{% endif %}
  - conditions:
      user: Gezin, redacted names
    config:
      show_tabs: 0 to 3,7,16 to 19
      voice_hide: true
      options_hide: true
  - conditions:
      user_agent: iPhone
    config:
      footer_mode: true
      indicator_top: false
      header_text: >-
         {{marquee}}
```
